import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {chromium,webkit} from 'playwright';
const server=createServer(async(req,res)=>{try{res.setHeader('Content-Type',req.url.endsWith('.js')?'text/javascript':'text/html');res.end(req.url==='/'?'<!doctype html><body></body>':await readFile(new URL('..'+req.url,import.meta.url)));}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
try{for(const engine of [chromium,webkit]){const browser=await engine.launch({headless:true});try{const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.address().port);const result=await page.evaluate(async()=>{
 const calls=[];class Native extends HTMLElement{constructor(){super();this.attachShadow({mode:'open'}).innerHTML='<div class="dash6-pod-error"></div>';}_handleClick(e){return this.hass.callService('media_player',e.currentTarget.getAttribute('action'),{entity_id:this._config.entity});}}
 customElements.define('hui-media-control-card',Native);await import('/src/dash6/homepod-power.js');await Promise.resolve();
 const id='media_player.example',remote='remote.assigned',card=new Native();card._config={entity:id};card.setAttribute('data-dash6-homepod','');card.hass={states:{[id]:{state:'off'},[remote]:{state:'off'},'remote.example':{state:'on'}},entities:{[id]:{entity_id:id,device_id:'pod',platform:'apple_tv'},[remote]:{entity_id:remote,device_id:'pod',platform:'apple_tv'},'remote.example':{entity_id:'remote.example',device_id:'other-device',platform:'apple_tv'}},callService:async(...args)=>calls.push(args)};document.body.append(card);
 card.updated();const startup=calls.length;const actual=document.createElement('button');actual.setAttribute('action','turn_on');actual.onclick=()=>calls.push(['duplicate-native']);card.shadowRoot.append(actual);actual.click();await Promise.resolve();const capture=calls.splice(0);for(const action of ['turn_on','turn_off','media_play']){const b=document.createElement('button');b.setAttribute('action',action);await card._handleClick({currentTarget:b});}
 card.hass.entities[remote].device_id='unrelated';const b=document.createElement('button');b.setAttribute('action','turn_on');await card._handleClick({currentTarget:b});
 card._config.homepod_remote_entity=remote;await card._handleClick({currentTarget:b});
 card.hass.callService=async()=>{throw new Error('Connection failed')};await card._handleClick({currentTarget:b});return {startup,capture,calls,error:card.shadowRoot.querySelector('.dash6-pod-error').textContent};
 });assert.equal(result.startup,0);assert.deepEqual(result.capture.map(c=>c.slice(0,2)),[['remote','turn_on']]);assert.deepEqual(result.calls.map(c=>c.slice(0,2)),[['remote','turn_on'],['remote','turn_off'],['media_player','media_play'],['media_player','turn_on'],['remote','turn_on']]);assert.equal(result.calls[0][2].entity_id,'remote.assigned');assert.equal(result.error,'Connection failed');console.log('PASS '+engine.name()+': HomePod connects through same-device remote, native playback preserved, unrelated remote rejected, explicit mapping and visible errors.');}finally{await browser.close();}}}finally{server.close();}
