import {suggestStats} from './stat-suggestions.js';
import {LitElement,html,css} from 'lit';
import {FIELDS,TYPE,normalizeConfig,defaultsFor,ID_MAP} from './config.js';
export class VacuumDockCardEditor extends LitElement {
 static properties={hass:{attribute:false},_config:{state:true},_step:{state:true},_notice:{state:true},_dockDevice:{state:true}};
 constructor(){super();this._config={type:TYPE,entities:{},areas:[],stats:{default:[],cleaning:[]},defaults:{}};this._step=0;this._notice='';this._dockDevice='';}
 setConfig(c){this._config={...structuredClone(c),entities:{...c.entities},defaults:{...c.defaults},areas:c.areas||[],stats:{default:[],cleaning:[],...c.stats}};}
 tr(de,en){return (this._config.language==='auto'||!this._config.language?(this.hass?.locale?.language||'en'):this._config.language).startsWith('de')?de:en;}
 change(path,value){const c=structuredClone(this._config);let obj=c;for(const k of path.slice(0,-1))obj=obj[k]??={};if(value===''||value===undefined)delete obj[path.at(-1)];else obj[path.at(-1)]=value;this._config=c;this.dispatchEvent(new CustomEvent('config-changed',{detail:{config:c},bubbles:true,composed:true}));}
 select(label,value,options,fn){return html`<label><span>${label}</span><select .value=${value??''} @change=${e=>fn(e.target.value)}><option value="">${this.tr('Nicht zugeordnet / automatisch','Not mapped / automatic')}</option>${value&&!options.some(o=>o.value===value)?html`<option .value=${value} selected>${value} (${this.tr('nicht verfügbar','unavailable')})</option>`:''}${options.map(o=>html`<option .value=${o.value} ?selected=${o.value===value}>${o.label}</option>`)}</select></label>`;}
 field(path,label,type='text'){const val=path.reduce((o,k)=>o?.[k],this._config);return html`<label><span>${label}</span><input type=${type} .value=${String(val??'')} @change=${e=>this.change(path,e.target.value===''?'':type==='number'?Number(e.target.value):e.target.value)}></label>`;}
 pick(path,label,domain){const value=path.reduce((o,k)=>o?.[k],this._config);const options=Object.values(this.hass?.states||{}).filter(s=>s.entity_id.startsWith(domain+'.')).sort((a,b)=>(a.attributes.friendly_name||a.entity_id).localeCompare(b.attributes.friendly_name||b.entity_id)).map(s=>({value:s.entity_id,label:(s.attributes.friendly_name||s.entity_id)+' · '+s.entity_id}));return this.select(label,value,options,v=>this.change(path,v));}
 async suggest(){
  try{const registry=await this.hass.callWS({type:'config/entity_registry/list'});const device=registry.find(e=>e.entity_id===this._config.entity)?.device_id;if(!device){this._notice=this.tr('Kein Gerät zur Vacuum-Entität gefunden. Bitte manuell zuordnen.','No device found for the vacuum. Map entities manually.');return;}
   const patterns={battery:/battery|batterie/,progress:/cleaning_progress|reinigungsfortschritt/,cleaning_mode:/cleaning_mode|reinigungsmodus/,mop_intensity:/mop_intensity|wisch_intensitat|mop_water_flow/,mop_route:/mop_mode|mop_route|wisch_modus/,mop_drying:/mop_drying|mopp_trocknung/,mop_washing:/mop_washing|moppwasche/,dust_emptying:/dust_emptying|staubentleerung/,drying_remaining:/mop_drying_remaining|verbleibende_zeit_zum_trocknen/,clean_water:/clean_water_tank|frischwassertank/,dirty_water:/dirty_water_tank|schmutzwassertank/,emptying_mode:/emptying_mode|entleerungsmodus/};
   const entities={...this._config.entities};let count=0;for(const [k,domain]of FIELDS){if(entities[k])continue;const target=['battery','progress','cleaning_mode','mop_intensity','mop_route'].includes(k)?device:(this._dockDevice||device);const matches=registry.filter(e=>e.device_id===target&&!e.disabled_by&&e.entity_id.startsWith(domain+'.')&&patterns[k].test(e.entity_id+' '+(e.translation_key||'')));if(matches.length===1){entities[k]=matches[0].entity_id;count++;}}
   this.change(['entities'],entities);this._notice=this.tr(count+' eindeutige Zuordnungen ergänzt. Bitte prüfen; vorhandene Zuordnungen wurden beibehalten.',count+' unambiguous mappings added. Please review; existing mappings were preserved.');
  }catch{this._notice=this.tr('Geräteregister nicht lesbar. Alle Entitäten können manuell ausgewählt werden.','Device registry unavailable. All entities can be selected manually.');}
 }
 async suggestStatistics(group){
  try {
   const registry=await this.hass.callWS({type:'config/entity_registry/list'});
   const robot=registry.find(e=>e.entity_id===this._config.entity)?.device_id;
   if(!robot){this._notice=this.tr('Kein Gerät zur Vacuum-Entität gefunden. Bitte manuell zuordnen.','No device found for the vacuum. Map entities manually.');return;}
   const dockIds=['mop_drying','mop_washing','dust_emptying','clean_water','dirty_water','emptying_mode'].map(k=>registry.find(e=>e.entity_id===this._config.entities[k])?.device_id).filter(Boolean);
   const distinct=[...new Set(dockIds)];
   const dock=this._dockDevice||(distinct.length===1?distinct[0]:undefined);
   const result=suggestStats({group,registry,states:this.hass.states||{},robot,dock,existing:this._config.stats[group],german:this.tr('de','en')==='de'});
   if(result.added)this.change(['stats',group],result.rows);
   this._notice=this.tr(`${result.added} Sensoren ergänzt; ${result.ambiguous} mehrdeutige Treffer ausgelassen. Vorhandene Zeilen bleiben erhalten. Bitte Zuordnung und Einheiten prüfen.`,`${result.added} sensors added; ${result.ambiguous} ambiguous matches skipped. Existing rows were preserved. Please review mappings and units.`);
  }catch{this._notice=this.tr('Geräteregister nicht lesbar. Bitte Sensoren manuell zuordnen.','Device registry unavailable. Map sensors manually.');}
 }
 render(){if(!this.hass)return html``;const steps=[this.tr('Roboter','Robot'),this.tr('Basisstation','Dock'),this.tr('Wartung','Statistics'),this.tr('Räume','Rooms'),this.tr('Standardwerte','Defaults')];let error='';try{normalizeConfig(this._config);}catch(e){error=e.message;}
 return html`<div class="intro"><strong>Vacuum Dock Card</strong><p>${this.tr('Ordne deine Entitäten zu. Nicht benötigte Funktionen bleiben leer und werden ausgeblendet.','Map your entities. Leave unused functions empty to hide them.')}</p></div><nav>${steps.map((s,i)=>html`<button aria-pressed=${String(i===this._step)} @click=${()=>this._step=i}>${i+1}. ${s}</button>`)}</nav>
 ${this._step===0?html`<div class="fields">${this.pick(['entity'],this.tr('Staubsauger (Pflicht)','Vacuum (required)'),'vacuum')}${this.field(['name'],this.tr('Kartenname (optional)','Card name (optional)'))}${this.select(this.tr('Sprache','Language'),this._config.language||'auto',['auto','de','en'].map(v=>({value:v,label:v})),v=>this.change(['language'],v||'auto'))}${FIELDS.slice(0,5).map(([k,d,de,en])=>this.pick(['entities',k],this.tr(de,en),d))}</div><button class="assist" ?disabled=${!this._config.entity} @click=${this.suggest}>${this.tr('Passende Entitäten vorschlagen','Suggest matching entities')}</button>`:''}
 ${this._step===1?html`<div class="fields">${this.select(this.tr('Dock-Gerät für Zuordnungsvorschläge','Dock device for suggestions'),this._dockDevice,Object.values(this.hass.devices||{}).map(d=>({value:d.id,label:d.name_by_user||d.name||d.id})),v=>this._dockDevice=v)}${FIELDS.slice(5).map(([k,d,de,en])=>this.pick(['entities',k],this.tr(de,en),d))}${this.select(this.tr('Einheit der Trocknungsrestzeit','Drying time unit'),this._config.drying_time_unit||'auto',['auto','s','min','h'].map(v=>({value:v,label:v})),v=>this.change(['drying_time_unit'],v||'auto'))}</div><button class="assist" ?disabled=${!this._config.entity} @click=${this.suggest}>${this.tr('Passende Entitäten vorschlagen','Suggest matching entities')}</button>`:''}
 ${this._step===2?html`${['default','cleaning'].map(group=>html`<h3>${group==='default'?this.tr('Wartungsrestzeiten','Maintenance remaining'):this.tr('Während der Reinigung','During cleaning')}</h3><button class="assist" ?disabled=${!this._config.entity} @click=${()=>this.suggestStatistics(group)}>${group==='default'?this.tr('Wartungssensoren vorschlagen','Suggest maintenance sensors'):this.tr('Reinigungssensoren vorschlagen','Suggest cleaning sensors')}</button>${this._config.stats[group].map((s,i)=>html`<section class="row"><div class="fields">${this.pick(['stats',group,i,'entity'],this.tr('Sensor','Sensor'),'sensor')}${this.field(['stats',group,i,'title'],this.tr('Beschriftung','Label'))}${this.field(['stats',group,i,'unit'],this.tr('Einheit (leer = Sensor)','Unit (empty = sensor)'))}${this.field(['stats',group,i,'scale'],this.tr('Nachkommastellen (0–5)','Decimal places (0–5)'),'number')}${this.field(['stats',group,i,'divide_by'],this.tr('Teilen durch (optional)','Divide by (optional)'),'number')}</div><button @click=${()=>this.change(['stats',group],this._config.stats[group].filter((_,n)=>n!==i))}>${this.tr('Entfernen','Remove')}</button></section>`)}<button @click=${()=>this.change(['stats',group],[...this._config.stats[group],{entity:'',scale:1}])}>+ ${this.tr('Sensor hinzufügen','Add sensor')}</button>`)}`:''}
 ${this._step===3?html`<p>${this.tr('Roborock-Segment-IDs gehören zur aktuell aktiven Karte des Roboters. HA-Bereiche und Roborock-IDs sind nicht identisch. Die Nummern müssen aus deiner Roborock-Karte stammen.','Roborock segment IDs belong to the active robot map. HA areas and Roborock IDs are not identical. Use IDs from your own robot map.')}</p>${this._config.areas.map((a,i)=>html`<section class="row"><div class="fields">${this.select(this.tr('HA-Bereich','HA area'),a.area_id,Object.values(this.hass.areas||{}).map(a=>({value:a.area_id,label:a.name})),v=>this.change(['areas',i,'area_id'],v))}${this.field(['areas',i,'name'],this.tr('Name (optional bei HA-Bereich)','Name (optional with HA area)'))}${this.field(['areas',i,'roborock_area_id'],this.tr('Roborock-Segment-ID','Roborock segment ID'),'number')}${this.field(['areas',i,'icon'],'Icon (mdi:...)')}</div><button @click=${()=>this.change(['areas'],this._config.areas.filter((_,n)=>n!==i))}>${this.tr('Entfernen','Remove')}</button></section>`)}<button @click=${()=>this.change(['areas'],[...this._config.areas,{name:'',roborock_area_id:null}])}>+ ${this.tr('Raum hinzufügen','Add room')}</button>`:''}
 ${this._step===4?html`<p>${this.tr('Leer = unterstützten Standard automatisch wählen. moderate bedeutet Mäßig; medium bedeutet Mittel. Durchgänge gelten nur für Raumreinigung.','Empty = choose a supported default automatically. moderate is distinct from medium. Cycles apply only to room cleaning.')}</p><div class="fields">${['mode','intensity','route','fan'].map(k=>{const id=k==='fan'?this._config.entity:this._config.entities[ID_MAP[k]],s=this.hass.states[id],options=k==='fan'?s?.attributes.fan_speed_list:s?.attributes.options;return this.select({mode:this.tr('Reinigungsmodus','Cleaning mode'),intensity:this.tr('Wisch-Intensität','Mop intensity'),route:this.tr('Wisch-Modus','Mop route'),fan:this.tr('Saugstufe','Fan speed')}[k],this._config.defaults[k],(options||[]).map(v=>({value:v,label:k==='fan'?(this.hass.formatEntityAttributeValue?.(s,'fan_speed',v)||v):(this.hass.formatEntityState?.({...s,state:v})||v)})),v=>this.change(['defaults',k],v));})}${this.select(this.tr('Durchgänge','Cycles'),String(this._config.defaults.repeat||1),[1,2,3].map(v=>({value:String(v),label:v+' ×'})),v=>this.change(['defaults','repeat'],Number(v)||1))}</div>`:''}
 ${this._notice?html`<p class="notice" role="status">${this._notice}</p>`:''}${error?html`<p class="error" role="status">${error}</p>`:''}<footer><button ?disabled=${this._step===0} @click=${()=>this._step--}>${this.tr('Zurück','Back')}</button><span>${this._step+1} / 5</span><button ?disabled=${this._step===4} @click=${()=>this._step++}>${this.tr('Weiter','Next')}</button></footer>`;
 }
 static styles=css`:host{display:block;color:var(--primary-text-color);font-family:inherit}*{box-sizing:border-box}.intro p,p{font-size:13px;line-height:1.6;color:var(--secondary-text-color)}nav{display:flex;flex-wrap:wrap;gap:8px;margin:16px 0}button{min-height:44px;padding:10px 14px;border:1px solid var(--divider-color,#555);border-radius:14px;background:var(--secondary-background-color,#292929);color:inherit;font:inherit;font-size:13px;cursor:pointer}button[aria-pressed=true],.assist{border-color:var(--primary-color);color:var(--primary-color)}button:disabled{opacity:.4;cursor:default}.fields{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}label{display:flex;flex-direction:column;gap:6px;font-size:13px;min-width:0}input,select{width:100%;min-height:48px;border:1px solid var(--divider-color,#555);border-radius:12px;padding:10px;background:var(--card-background-color,#222);color:inherit;font:inherit}button:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid var(--primary-color);outline-offset:2px}.assist{margin-top:16px}.row{padding:14px;border:1px solid var(--divider-color,#555);border-radius:16px;margin:12px 0}.row>button{margin-top:12px}.error{color:var(--error-color,#e55)}.notice{padding:12px;border:1px solid var(--divider-color);border-radius:12px}footer{display:flex;justify-content:space-between;align-items:center;margin-top:20px;font-size:13px}h3{font-size:15px;font-weight:500}`;
}
if(!customElements.get('vacuum-dock-card-editor'))customElements.define('vacuum-dock-card-editor',VacuumDockCardEditor);
