import {LitElement,html,css} from 'lit';
const clone=x=>structuredClone(x);
export const EDITOR_VERSION='2026.10.04-36';
const labels={entity:'Haupt-Entity',name:'Anzeigename',icon:'Icon',title:'Titel',modes:'Betriebsmodi',graph:'Hintergrundgraph',controls:'Bedienelemente',discovery:'Automatische Zuordnung',segments:'Enthaltene Lichter',segment_excludes:'Ausgeschlossene Lichter',feedback:'Rückmeldung',scenes:'Szenen',main_back:'Hauptlicht und Backlight',skin:'Darstellung',css:'CSS',definition:'Kartenkonfiguration',card:'Eingebettete Karte',cards:'Enthaltene Karten',conditions:'Bedingungen',filter:'Dynamischer Filter',template:'Dynamisches Template',tap_action:'Tippen',hold_action:'Gedrückt halten',double_tap_action:'Doppeltippen',power_entity:'Leistungssensor',energy_entity:'Energiesensor',child_lock_entity:'Kindersicherung',led_entity:'LED-Schalter',area:'Bereich',room:'Raumname',show:'Anzeigen',height:'Höhe',interval:'Aggregation',update_interval:'Aktualisierung',span:'Zeitraum',minimum:'Mindestskala',color:'Farbe',source:'Datenquelle'};
export function selectorFor(key,value){if(typeof value==='boolean')return {boolean:{}};if(typeof value==='number')return {number:{mode:'box',step:'any'}};if(key==='icon')return {icon:{}};if(/(^entity$|_entity$|_remote$)/.test(key)&&!String(value).includes('[[['))return {entity:{}};if(/^(area|area_id)$/.test(key))return {area:{}};return {text:{multiline:typeof value==='string'&&(value.includes('\n')||value.length>180)}};}
export class ConfigEditor extends LitElement{
 static properties={hass:{attribute:false},_config:{state:true},schema:{attribute:false},defaults:{attribute:false}};
 static styles=css`:host{display:block;min-width:0}details{margin:8px 0;padding:8px;border:1px solid var(--divider-color);border-radius:12px}summary{cursor:pointer;min-height:32px;font-weight:600}.field{display:grid;grid-template-columns:minmax(0,1fr) 36px;gap:4px;margin:8px 0}.tools{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}button{min-height:36px;cursor:pointer;color:var(--primary-text-color);background:var(--secondary-background-color);border:1px solid var(--divider-color);border-radius:8px}input,select{max-width:100%;min-height:36px;box-sizing:border-box}.hint{font-size:12px;color:var(--secondary-text-color)}.key{min-width:0;flex:1}`;
 schema=[];defaults={};
 setConfig(c){this._config=clone(c);}
 emit(c){this._config=c;this.dispatchEvent(new CustomEvent('config-changed',{detail:{config:clone(c)},bubbles:true,composed:true}));}
 change(path,value,remove=false){const next=clone(this._config);let target=next;for(const key of path.slice(0,-1))target=target[key]??={};const key=path.at(-1);if(remove){if(Array.isArray(target))target.splice(Number(key),1);else delete target[key];}else target[key]=value;this.emit(next);}
 primitive(key,value,path,definition){const schema=definition||{name:'value',label:labels[key]||key,selector:selectorFor(key,value)};return html`<div class="field"><ha-form .hass=${this.hass} .data=${{[schema.name]:value}} .schema=${[schema]} .computeLabel=${x=>x.label||labels[key]||key} @value-changed=${e=>{e.stopPropagation();const v=e.detail.value[schema.name];if(v===undefined)this.change(path,null,true);else this.change(path,v)}}></ha-form><button title="Auf Vorgabe zurücksetzen / entfernen" aria-label=${(labels[key]||key)+' entfernen'} @click=${()=>this.change(path,null,true)}>×</button></div>`;}
 object(value,path=[],title='Alle Einstellungen',open=false){const array=Array.isArray(value);return html`<details ?open=${open}><summary>${title}${array?' · '+value.length:''}</summary>${path.length&&typeof value.type==='string'&&(path.at(-1)==='card'||path.at(-1)==='definition'||path.at(-2)==='cards')?html`<dash6-inline-editor .hass=${this.hass} .config=${value} @config-changed=${e=>{e.stopPropagation();this.change(path,e.detail.config)}}></dash6-inline-editor>`:''}${Object.entries(value).filter(([k])=>k!=='type'||path.length).map(([key,v])=>v!==null&&typeof v==='object'?this.object(v,[...path,key],labels[key]||key):this.primitive(key,v,[...path,key]))}${this.add(value,path)}${path.length?html`<button @click=${()=>this.change(path,null,true)}>Abschnitt entfernen</button>`:''}</details>`;}
 add(value,path){const array=Array.isArray(value);return html`<div class="tools">${array?'':html`<input class="key" aria-label="Einstellung hinzufügen" placeholder="Name der Einstellung">`}<select aria-label="Datentyp"><option value="text">Text</option><option value="boolean">Ein/Aus</option><option value="number">Zahl</option><option value="object">Unterabschnitt</option><option value="array">Liste</option></select><button @click=${e=>{const root=e.currentTarget.parentElement;const key=array?value.length:root.querySelector('input').value.trim();if(key===''||['__proto__','prototype','constructor'].includes(key)||Object.hasOwn(value,key))return;const type=root.querySelector('select').value;this.change([...path,key],{text:'',boolean:false,number:0,object:{},array:[]}[type])}}>Hinzufügen</button></div>`;}
 render(){if(!this._config)return html``;const missing=this.schema.filter(s=>!Object.hasOwn(this._config,s.name));return html`<p class="hint">Karteneditor ${EDITOR_VERSION} · Änderungen werden mit der Karte gespeichert.</p>${missing.map(s=>this.primitive(s.name,this.defaults[s.name], [s.name],s))}${this.object(this._config,[],'Alle Einstellungen',true)}<p class="hint">Listen und Unterabschnitte sind einzeln bearbeitbar. Templates, JavaScript und CSS bleiben Textfelder.</p>`;}
}
customElements.define('dash6-config-editor',ConfigEditor);
