import {LitElement,html,css} from 'lit';
import {surface,bindThemePreferences,unbindThemePreferences} from './material.js';
import {errorIndicator,reportError} from './error-indicator.js';
const valid=s=>!!s&&!['unknown','unavailable'].includes(s.state);
export function doorActions(lock,contact){
 const state=lock?.state,known=valid(lock),opened=['open','opening'].includes(state);
 return {head:['open','opening','unlocked','unlocking'].includes(state)?'lock':'open',right:state==='locked'?'unlock':'lock',hideOpen:opened,canOpen:known&&contact?.state==='off'&&!opened&&!['locking','unlocking'].includes(state),canLock:known&&!['locking','unlocking','opening'].includes(state)};
}
export function recentRing(event,pressed,now=Date.now()){
 const time=Date.parse(event?.state),reset=Date.parse(pressed?.state);
 return Number.isFinite(time)&&now>=time&&now-time<60000&&(!Number.isFinite(reset)||reset<time);
}
class DoorCard extends LitElement {
 static properties={hass:{attribute:false},_busy:{state:true},_tick:{state:true}};
 static styles=css`:host{display:block;min-width:0}ha-card{overflow:hidden;padding:8px;box-sizing:border-box}.head{display:grid;grid-template-columns:48px minmax(0,1fr) auto;align-items:center;gap:8px;width:100%;padding:0 4px 8px;text-align:left;background:transparent!important;border:0!important;box-shadow:none!important;backdrop-filter:none!important;scale:1!important;translate:none!important;cursor:pointer;color:inherit;font:inherit}.lens{display:grid;place-items:center;width:44px;height:44px;box-sizing:border-box;border-radius:14px;background:var(--dash6-icon-lens-background,var(--dash6-button-background));border:var(--dash6-icon-lens-border,var(--dash6-button-border));box-shadow:var(--dash6-icon-lens-shadow,var(--dash6-button-shadow));backdrop-filter:var(--dash5-control-backdrop);-webkit-backdrop-filter:var(--dash5-control-backdrop)}ha-icon{--mdc-icon-size:22px}.text{min-width:0}.name{display:block;font-size:18px;font-weight:650;line-height:26px}.status{display:block;font-size:13px;line-height:20px;color:var(--secondary-text-color);overflow-wrap:anywhere}.actions{display:grid;grid-template-columns:2fr 1fr;gap:8px}.actions.single{grid-template-columns:1fr}.action{display:flex;align-items:center;justify-content:center;gap:8px;min-height:48px;padding:8px 12px;font:inherit;cursor:pointer;box-sizing:border-box}.action:disabled{opacity:.6;cursor:default}.head:disabled{cursor:default}.warning{color:var(--error-color);display:flex;gap:4px;align-items:center;font-size:12px}.warning ha-icon{--mdc-icon-size:18px}.ring{color:var(--error-color)}.unlocked{color:var(--error-color)}.open{color:var(--error-color)}@media(max-width:599px){.actions{grid-template-columns:1fr}}`;
 setConfig(c){if(!c.entity?.startsWith(c.kind==='entrance'?'button.':'lock.'))throw Error('Passende Tür-Entität auswählen.');this._config={...c};this.requestUpdate();}
 static getConfigElement(){const e=document.createElement('dash6-basic-editor');e.schema=[{name:'kind',label:'Türtyp',selector:{select:{options:[{value:'apartment',label:'Wohnungstür / Schloss'},{value:'entrance',label:'Haustür / Öffner'}]}}},{name:'entity',label:'Schloss oder Öffner',selector:{entity:{domain:['lock','button']}}},{name:'name',label:'Anzeigename',selector:{text:{}}},{name:'contact_entity',label:'Türkontakt',selector:{entity:{domain:'binary_sensor'}}},{name:'battery_entity',label:'Batterie',selector:{entity:{domain:'sensor'}}},{name:'contact_battery_entity',label:'Türkontakt-Batterie',selector:{entity:{domain:'sensor'}}},{name:'battery_warning_entity',label:'Schloss-Batteriewarnung',selector:{entity:{domain:'binary_sensor'}}},{name:'activity_entity',label:'Letzte Aktivität',selector:{entity:{domain:'sensor'}}},{name:'ring_entity',label:'Klingelereignis',selector:{entity:{domain:'event'}}}];return e;}
 connectedCallback(){super.connectedCallback();bindThemePreferences(this);this._timer=setInterval(()=>{this._tick=Date.now()},1000);}
 disconnectedCallback(){super.disconnectedCallback();unbindThemePreferences(this);clearInterval(this._timer);}
 getCardSize(){return 2;}
 warning(id,threshold=25){const raw=this.hass?.states[id]?.state,n=Number.parseFloat(raw);return Number.isFinite(n)&&n<=threshold?html`<span class="warning" title=${this.hass.states[id]?.attributes.friendly_name||'Batterie'}><ha-icon icon="mdi:battery-alert-variant-outline"></ha-icon>${n}%</span>`:'';}
 async act(action){if(this._busy||!this.hass)return;const c=this._config,s=this.hass.states[c.entity],a=doorActions(s,this.hass.states[c.contact_entity]);if(c.kind==='entrance'){if(!s||s.state==='unavailable')return;action='press';}else if(action==='head')action=a.head;if(c.kind!=='entrance'&&!(action==='open'?a.canOpen:a.canLock))return;this._busy=true;try{await this.hass.callService(c.kind==='entrance'?'button':'lock',action,{entity_id:c.entity})}catch(error){reportError(this,error)}finally{this._busy=false;}}
 render(){const c=this._config,s=this.hass?.states[c?.entity];if(!c||!this.hass)return html``;const entrance=c.kind==='entrance',contact=this.hass.states[c.contact_entity],a=doorActions(s,contact),ring=entrance&&recentRing(this.hass.states[c.ring_entity],s),lockState=s?.state;
 const labels={locked:'Abgeschlossen',unlocked:'Aufgeschlossen',locking:'Wird abgeschlossen …',unlocking:'Wird aufgeschlossen …',opening:'Wird geöffnet …',open:'Geöffnet',unknown:'Status unbekannt',unavailable:'Nicht verfügbar'};
 const activity=this.hass.states[c.activity_entity]?.state,time=Date.parse(activity),status=entrance?'Geklingelt: '+(Number.isFinite(time)?new Intl.DateTimeFormat('de-DE',{hour:'2-digit',minute:'2-digit'}).format(time)+' Uhr':'keine Aktivität bekannt'):contact?.state==='on'?(lockState==='unlocked'?'Geöffnet und aufgeschlossen':'Tür geöffnet'):(labels[lockState]||'Status unbekannt');
 const ico=entrance?'mdi:doorbell-video':contact?.state==='on'||a.hideOpen?'mdi:door-open':['unlocked','unlocking'].includes(lockState)?'mdi:lock-open-variant':lockState==='locking'?'mdi:lock-clock':'mdi:lock';
 return html`<style>${surface}</style><ha-card><button class="head detail-link" aria-label=${c.name|| (entrance?'Haustür':'Wohnungstür')} ?disabled=${this._busy||(entrance?(!s||s.state==='unavailable'):!(a.head==='open'?a.canOpen:a.canLock))} @click=${()=>this.act('head')}><span class=${'lens '+(ring?'ring':!entrance&&lockState!=='locked'?'unlocked':'')}><ha-icon icon=${ico}></ha-icon></span><span class="text"><span class="name">${c.name||(entrance?'Haustür':'Wohnungstür')}</span><span class="status">${status}</span></span><span>${this.warning(c.battery_entity,entrance?25:24.999)}${this.warning(c.contact_battery_entity,24.999)}${this.hass.states[c.battery_warning_entity]?.state==='on'?html`<span class="warning"><ha-icon icon="mdi:battery-alert-variant-outline"></ha-icon></span>`:''}</span></button><div style="display:flex;justify-content:flex-end">${errorIndicator(this)}</div><div class=${'actions '+(entrance||a.hideOpen?'single':'')}>${entrance||!a.hideOpen?html`<button class=${'action '+(contact?.state==='on'?'open':'')} ?disabled=${this._busy||(entrance?(!s||s.state==='unavailable'):!a.canOpen)} @click=${()=>this.act('open')}><ha-icon icon="mdi:door-open"></ha-icon>Öffnen</button>`:''}${!entrance?html`<button class="action" aria-label=${a.right==='unlock'?'Aufschließen':'Abschließen'} title=${a.right==='unlock'?'Aufschließen':'Abschließen'} ?disabled=${this._busy||!a.canLock} @click=${()=>this.act(a.right)}><ha-icon icon=${a.right==='unlock'?'mdi:lock-open-variant':'mdi:lock'}></ha-icon></button>`:''}</div></ha-card>`;
 }
}
customElements.define('dash6-door-card',DoorCard);
window.customCards??=[];window.customCards.push({type:'dash6-door-card',name:'DASH6 Tür und Schloss',description:'Liquid-Glass-Türkarte mit Türkontakt, Batterie und getrennten Schlossaktionen.',preview:true});
