import {LitElement,html,css} from 'lit';
import {surface,bindThemePreferences,unbindThemePreferences} from './material.js';
import {errorIndicator,reportError} from './error-indicator.js';
const valid=s=>!!s&&!['unknown','unavailable'].includes(s.state);
export function doorActions(lock,contact){
 const state=lock?.state,known=valid(lock),opened=['open','opening'].includes(state);
 return {head:['open','opening','unlocked','unlocking'].includes(state)?'lock':'open',right:state==='locked'?'unlock':'lock',hideOpen:opened,canOpen:known&&contact?.state==='off'&&!opened&&!['locking','unlocking'].includes(state),canLock:known&&!['locking','unlocking','opening'].includes(state)};
}
export function ringTimestamp(event){
 if(!event)return NaN;
 if(event.entity_id?.startsWith('binary_sensor.'))return event.state==='on'?Date.parse(event.last_changed):NaN;
 return Date.parse(event.state);
}
export function recentRing(event,pressed,now=Date.now()){
 const time=ringTimestamp(event),reset=Date.parse(pressed?.state);
 return Number.isFinite(time)&&now>=time&&now-time<60000&&(!Number.isFinite(reset)||reset<time);
}
export function doorTone(config,states,now=Date.now(),dismissed=0,remembered=0,opened=0){
 const contact=states[config.contact_entity];
 if(config.kind!=='entrance')return contact?.state==='on'?'open':contact?.state!=='off'?'neutral':states[config.entity]?.state==='locked'?'locked':states[config.entity]?.state==='unlocked'?'unlocked':'neutral';
 const ring=Math.max(remembered,...[config.ring_entity,...(config.ring_entities||[])].filter(Boolean).map(id=>ringTimestamp(states[id])).filter(Number.isFinite));
 const handled=Math.max(dismissed,...(config.cancel_entities||[config.entity]).map(id=>{const state=states[id];return id?.startsWith('button.')?Date.parse(state?.state)||0:Date.parse(state?.last_changed)||0;}));
 const contactChange=Math.max(opened,contact?.state==='on'?Date.parse(contact.last_changed)||0:0);
 return Number.isFinite(ring)&&now>=ring&&now-ring<60000&&handled<ring&&contactChange<ring?'ring':'neutral';
}
class DoorCard extends LitElement {
 static properties={hass:{attribute:false},_busy:{state:true},_tick:{state:true}};
 willUpdate(changed){if(changed.has('hass')&&this.hass){const c=this._config;if(c?.kind==='entrance'){const times=[c.ring_entity,...(c.ring_entities||[])].filter(Boolean).map(id=>ringTimestamp(this.hass.states[id])).filter(Number.isFinite);this._lastRing=Math.max(this._lastRing||0,...times);const contact=this.hass.states[c.contact_entity];if(contact?.state==='on')this._lastOpened=Math.max(this._lastOpened||0,Date.parse(contact.last_changed)||0);this.subscribeActions();}}}
 subscribeActions(){if(this._eventsConnection===this.hass.connection)return;this._unsubscribeActions?.();this._eventsConnection=this.hass.connection;const generation=this._eventsGeneration=(this._eventsGeneration||0)+1;this.hass.connection?.subscribeEvents?.(event=>{const data=event.data||{},ids=[data.service_data?.entity_id,data.target?.entity_id].flat().filter(Boolean),c=this._config;if(ids.some(id=>(c.cancel_entities||[c.entity]).includes(id))){this._dismissed=Date.parse(event.time_fired)||Date.now();this._tick=Date.now();}},'call_service').then(unsubscribe=>{if(!this.isConnected||generation!==this._eventsGeneration)unsubscribe();else this._unsubscribeActions=unsubscribe;}).catch(()=>{});}
 static styles=css`ha-card{position:relative;isolation:isolate}ha-card>.tint{position:absolute;inset:0;z-index:0;border-radius:inherit;pointer-events:none;background:transparent}ha-card>.head,ha-card>.actions,ha-card>.errors{position:relative;z-index:2}ha-card[data-tone=locked]>.tint{background:rgba(15,90,47,.32)}ha-card[data-tone=unlocked]>.tint{background:rgba(120,20,32,.32)}ha-card[data-tone=open]>.tint{background:rgba(215,50,65,.38);animation:door-pulse 2s ease-in-out infinite}ha-card[data-tone=ring]>.tint{background:rgba(255,152,0,.38);animation:door-pulse 2s ease-in-out infinite}@keyframes door-pulse{0%,100%{opacity:0}50%{opacity:1}}@media(prefers-reduced-motion:reduce){ha-card>.tint{animation:none!important;opacity:.65}}:host{display:block;min-width:0}ha-card{overflow:hidden;padding:8px;box-sizing:border-box}.head{display:grid;grid-template-columns:48px minmax(0,1fr) auto;align-items:center;gap:8px;width:100%;padding:0 4px 8px;text-align:left;background:transparent!important;border:0!important;box-shadow:none!important;backdrop-filter:none!important;scale:1!important;translate:none!important;cursor:pointer;color:inherit;font:inherit}.lens{display:grid;place-items:center;width:44px;height:44px;box-sizing:border-box;border-radius:14px;background:var(--dash6-icon-lens-background,var(--dash6-button-background));border:var(--dash6-icon-lens-border,var(--dash6-button-border));box-shadow:var(--dash6-icon-lens-shadow,var(--dash6-button-shadow));backdrop-filter:var(--dash5-control-backdrop);-webkit-backdrop-filter:var(--dash5-control-backdrop)}ha-icon{--mdc-icon-size:22px}.text{min-width:0}.name{display:block;font-size:18px;font-weight:650;line-height:26px}.status{display:block;font-size:13px;line-height:20px;color:var(--secondary-text-color);overflow-wrap:anywhere}.actions{display:grid;grid-template-columns:2fr 1fr;gap:8px}.actions.single{grid-template-columns:1fr}.action{display:flex;align-items:center;justify-content:center;gap:8px;min-height:48px;padding:8px 12px;font:inherit;cursor:pointer;box-sizing:border-box}.action:disabled{opacity:.6;cursor:default}.head:disabled{cursor:default}.warning{color:var(--error-color);display:flex;gap:4px;align-items:center;font-size:12px}.warning ha-icon{--mdc-icon-size:18px}.ring{color:var(--error-color)}.unlocked{color:var(--error-color)}.open{color:var(--error-color)}@media(max-width:599px){.actions{grid-template-columns:1fr}}`;
 setConfig(c){if(!c.entity?.startsWith(c.kind==='entrance'?'button.':'lock.'))throw Error('Passende Tür-Entität auswählen.');this._config={...c};this.requestUpdate();}
 static getConfigElement(){const e=document.createElement('dash6-basic-editor');e.schema=[{name:'kind',label:'Türtyp',selector:{select:{options:[{value:'apartment',label:'Wohnungstür / Schloss'},{value:'entrance',label:'Haustür / Öffner'}]}}},{name:'entity',label:'Schloss oder Öffner',selector:{entity:{domain:['lock','button']}}},{name:'name',label:'Anzeigename',selector:{text:{}}},{name:'contact_entity',label:'Türkontakt',selector:{entity:{domain:'binary_sensor'}}},{name:'battery_entity',label:'Batterie',selector:{entity:{domain:'sensor'}}},{name:'contact_battery_entity',label:'Türkontakt-Batterie',selector:{entity:{domain:'sensor'}}},{name:'battery_warning_entity',label:'Schloss-Batteriewarnung',selector:{entity:{domain:'binary_sensor'}}},{name:'activity_entity',label:'Letzte Aktivität',selector:{entity:{domain:'sensor'}}},{name:'ring_entity',label:'Klingelereignis',selector:{entity:{domain:['event','binary_sensor']}}},{name:'ring_entities',label:'Weitere Klingelsensoren',selector:{entity:{domain:['event','binary_sensor'],multiple:true}}},{name:'cancel_entities',label:'Türöffner und Schloss beenden Klingelsignal',selector:{entity:{domain:['button','lock'],multiple:true}}}];return e;}
 connectedCallback(){super.connectedCallback();bindThemePreferences(this);this._timer=setInterval(()=>{this._tick=Date.now()},1000);}
 disconnectedCallback(){super.disconnectedCallback();unbindThemePreferences(this);clearInterval(this._timer);this._eventsGeneration=(this._eventsGeneration||0)+1;this._unsubscribeActions?.();this._eventsConnection=null;}
 getCardSize(){return 2;}
 warning(id,threshold=25){const raw=this.hass?.states[id]?.state,n=Number.parseFloat(raw);return Number.isFinite(n)&&n<=threshold?html`<span class="warning" title=${this.hass.states[id]?.attributes.friendly_name||'Batterie'}><ha-icon icon="mdi:battery-alert-variant-outline"></ha-icon>${n}%</span>`:'';}
 async act(action){if(this._busy||!this.hass)return;const c=this._config,s=this.hass.states[c.entity],a=doorActions(s,this.hass.states[c.contact_entity]);if(c.kind==='entrance'){if(!s||s.state==='unavailable')return;action='press';}else if(action==='head')action=a.head;if(c.kind!=='entrance'&&!(action==='open'?a.canOpen:a.canLock))return;this._busy=true;if(c.kind==='entrance'){this._dismissed=Date.now();this._tick=Date.now();}try{await this.hass.callService(c.kind==='entrance'?'button':'lock',action,{entity_id:c.entity})}catch(error){reportError(this,error)}finally{this._busy=false;}}
 render(){const c=this._config,s=this.hass?.states[c?.entity];if(!c||!this.hass)return html``;const entrance=c.kind==='entrance',contact=this.hass.states[c.contact_entity],a=doorActions(s,contact),tone=doorTone(c,this.hass.states,Date.now(),this._dismissed||0,this._lastRing||0,this._lastOpened||0),ring=tone==='ring',lockState=s?.state;
 const labels={locked:'Abgeschlossen',unlocked:'Aufgeschlossen',locking:'abschließen ...',unlocking:'aufschließen ...',opening:'öffnen ...',open:'Geöffnet',unknown:'Status unbekannt',unavailable:'Nicht verfügbar'};
 const activity=this.hass.states[c.activity_entity]?.state,time=Date.parse(activity),status=entrance?'Klingel: '+(Number.isFinite(time)?new Intl.DateTimeFormat('de-DE',{hour:'2-digit',minute:'2-digit'}).format(time)+' Uhr':'keine Aktivität bekannt'):contact?.state==='on'?(lockState==='unlocked'?'Geöffnet und aufgeschlossen':'Tür geöffnet'):(labels[lockState]||'Status unbekannt');
 const ico=entrance?'mdi:doorbell-video':contact?.state==='on'||a.hideOpen?'mdi:door-open':['unlocked','unlocking'].includes(lockState)?'mdi:lock-open-variant':lockState==='locking'?'mdi:lock-clock':'mdi:lock';
 return html`<style>${surface}</style><ha-card data-tone=${tone}><span class="tint" aria-hidden="true"></span><div class=${entrance?'head entrance':'head'}>${entrance?html`<span class="lens"><ha-icon icon=${ico}></ha-icon></span>`:html`<dash6-glass-switch .managed=${true} ._config=${{entity:'switch.door_status',icon:this.doorSwitchModel().on?'mdi:lock':'mdi:lock-open-variant'}} .visual=${this.doorSwitchModel()} @toggle-request=${event=>{event.stopPropagation();this.act(entrance?'open':lockState==='locked'?'unlock':'lock')}}></dash6-glass-switch>`}<button class="text detail-link" @click=${()=>this.act('head')}><span class="name">${c.name||(entrance?'Haustür':'Wohnungstür')}</span><span class="status">${status}</span></button><span>${this.warning(c.battery_entity,entrance?25:24.999)}${this.warning(c.contact_battery_entity,24.999)}${this.hass.states[c.battery_warning_entity]?.state==='on'?html`<span class="warning"><ha-icon icon="mdi:battery-alert-variant-outline"></ha-icon></span>`:''}</span></div><div class="errors" style="display:flex;justify-content:flex-end">${errorIndicator(this)}</div><div class=${'actions '+(entrance||a.hideOpen?'single':'')}>${entrance||!a.hideOpen?html`<button class=${'action '+(contact?.state==='on'?'open':'')} ?disabled=${this._busy||(entrance?(!s||s.state==='unavailable'):!a.canOpen)} @click=${()=>this.act('open')}><ha-icon icon="mdi:door-open"></ha-icon>Öffnen</button>`:''}${!entrance?html`<button class="action" aria-label=${a.right==='unlock'?'Aufschließen':'Abschließen'} title=${a.right==='unlock'?'Aufschließen':'Abschließen'} ?disabled=${this._busy||!a.canLock} @click=${()=>this.act(a.right)}><ha-icon icon=${a.right==='unlock'?'mdi:lock-open-variant':'mdi:lock'}></ha-icon></button>`:''}</div></ha-card>`;
 }
}
customElements.define('dash6-door-card',DoorCard);
window.customCards??=[];window.customCards.push({type:'dash6-door-card',name:'DASH6 Tür und Schloss',description:'Liquid-Glass-Türkarte mit Türkontakt, Batterie und getrennten Schlossaktionen.',preview:true});
