import './external-editor.js';
import {css,unsafeCSS,html} from 'lit';
import BASE_CSS from './base.css';
const sectionsCSS=css`
.container{padding:0!important}
.wrapper{padding:0!important;margin:0!important;max-width:none!important;--column-count:10!important;--content-column-count:10!important;--column-gap:8px!important;overflow-anchor:none!important}
.content{display:grid!important;grid-template-columns:repeat(10,minmax(0,1fr))!important;column-gap:8px!important;row-gap:8px!important;align-items:start!important}
.content>.section{min-width:0!important;overflow-anchor:none!important}.content>.section[data-dash6-section-empty]{display:none!important}.content[data-dash6-compact]{grid-template-columns:minmax(0,1fr)!important}.content[data-dash6-compact]>.section:nth-child(n){grid-column:1 / -1!important;grid-row:auto!important}
.content>.section:nth-child(1){grid-column:5 / -1!important;grid-row:1!important}
.content>.section:nth-child(2){grid-column:1 / span 4!important;grid-row:1!important}
.content>.section:nth-child(3){grid-column:1 / span 4!important;grid-row:2!important}
.content>.section:nth-child(4){grid-column:5 / -1!important;grid-row:2!important}
.content>.section:nth-child(n+5){grid-column:1 / -1!important}
@media(max-width:599px){.content{grid-template-columns:minmax(0,1fr)!important}.content>.section:nth-child(n){grid-column:1 / -1!important;grid-row:auto!important}}
`;
customElements.whenDefined('hui-sections-view').then(()=>{const Base=customElements.get('hui-sections-view');class Sections extends Base{static styles=[Base.styles,sectionsCSS];constructor(){super();this.addEventListener('card-visibility-changed',()=>requestAnimationFrame(()=>this.syncSections()));}updated(changed){super.updated?.(changed);this.syncSections();}syncSections(){const content=this.shadowRoot?.querySelector('.content');if(!content)return;const sections=[...content.querySelectorAll(':scope>.section')];const collect=(root,out=[])=>{for(const e of root.querySelectorAll('*')){if(e.localName==='dash6-auto-entities')out.push(e);else if(e.shadowRoot)collect(e.shadowRoot,out);}return out;};for(const section of sections){const cards=collect(section);const staticContent=section.querySelectorAll('dash6-media-card').length>0||(()=>{let found=false;const scan=r=>{for(const e of r.querySelectorAll('*')){if(e.localName==='dash6-media-card')found=true;if(e.shadowRoot)scan(e.shadowRoot)}};scan(section);return found})();const empty=!staticContent&&cards.length>0&&cards.every(c=>c._dash6Signature&&c.empty);section.toggleAttribute('data-dash6-section-empty',empty);}content.toggleAttribute('data-dash6-compact',[sections[1],sections[2]].some(s=>s?.hasAttribute('data-dash6-section-empty')));}}customElements.define('dash6-sections-view',Sections)});
customElements.whenDefined('ultra-card').then(()=>{const Base=customElements.get('ultra-card');class Ultra extends Base{static styles=[Base.styles,unsafeCSS(BASE_CSS),css`ha-card{background:transparent!important;border:0!important;box-shadow:none!important;backdrop-filter:none!important;overflow:visible!important;padding:0!important}:host{overflow-anchor:none;min-width:0;max-width:100%}.card-column{min-width:0!important}.card-row{gap:8px!important}.card-column{gap:8px!important}.external-card-module-container{margin:0!important;min-width:0!important;max-width:100%}@media(min-width:1000px){.responsive-row-embedded-room-layout{grid-template-columns:minmax(0,1fr) 250px!important}.responsive-col-embedded-sidebar{display:flex!important;width:250px!important;min-width:250px!important}}@media(max-width:999px){.responsive-row-embedded-room-layout{grid-template-columns:minmax(0,1fr)!important;column-gap:0!important}.responsive-col-embedded-sidebar{display:none!important}.responsive-col-embedded-content{width:100%!important;min-width:0!important;max-width:100%!important}}.rows,.row-container,.layout-container{row-gap:8px!important}.column,.modules-container{gap:max(8px,var(--dash6-entity-gap,8px))!important}`];static async getConfigElement(){const editor=await Base.getConfigElement();const original=editor.setConfig.bind(editor);editor.setConfig=c=>original({...c,type:'custom:ultra-card'});editor.addEventListener('config-changed',e=>{e.detail.config.type='custom:dash6-ultra-card'});
const prior=editor.updated?.bind(editor);editor.updated=function(changed){prior?.(changed);const tab=this.shadowRoot?.querySelector('ultra-layout-tab');if(!tab||tab.__dash6Editor)return;tab.__dash6Editor=true;const panel=tab._renderModuleSettingsPanel.bind(tab),general=tab._renderGeneralTab.bind(tab),yaml=tab._renderYamlTab.bind(tab);
const isOwn=m=>m?.type==='external_card'&&!!m.card_config?.type;
const form=m=>{const key=m.id||JSON.stringify(tab._selectedModule);if(tab.__dash6FormKey!==key){tab.__dash6FormKey=key;tab.__dash6Form=document.createElement('dash6-external-editor');tab.__dash6Form.setConfig(m.card_config);tab.__dash6FormConfig=JSON.stringify(m.card_config);tab.__dash6Form.addEventListener('config-changed',e=>{e.stopPropagation();if(tab.__dash6FormKey!==key)return;tab.__dash6FormConfig=JSON.stringify(e.detail.config);tab._updateModule({card_config:e.detail.config})})}else if(tab.__dash6FormConfig!==JSON.stringify(m.card_config)){tab.__dash6FormConfig=JSON.stringify(m.card_config);tab.__dash6Form.setConfig(m.card_config);}tab.__dash6Form.hass=tab.hass;return html`<div class="settings-section">${tab.__dash6Form}</div>`};
tab._renderGeneralTab=m=>isOwn(m)?form(m):general(m);tab._renderYamlTab=m=>isOwn(m)?html`${form(m)}<details><summary>Erweiterte YAML-Konfiguration</summary>${yaml(m)}</details>`:yaml(m);
tab._renderModuleSettingsPanel=function(){const idx=this._selectedModule;const m=idx&&this.config.layout?.rows[idx.rowIndex]?.columns[idx.columnIndex]?.modules[idx.moduleIndex];if(!isOwn(m))return panel();const key=m.id||JSON.stringify(idx);if(this.__dash6Selected!==key){this.__dash6Selected=key;this._activeModuleTab='general'}const type=m.card_type;m.card_type='hui-dash6-profile-card';try{return panel()}finally{m.card_type=type}};tab.requestUpdate();};return editor}setConfig(c){const clean=structuredClone(c);clean.type='custom:ultra-card';delete clean.card_mod;super.setConfig(clean)}}customElements.define('dash6-ultra-card',Ultra);window.customCards??=[];window.customCards.push({type:'dash6-ultra-card',name:'DASH6 Ultra-Card',description:'Native Ultra-Card-GUI mit transparentem Strukturrahmen.',preview:false})});
customElements.whenDefined('grid-layout').then(()=>{const Base=customElements.get('grid-layout');class Pills extends Base{static styles=[Base.styles,css`#root{display:flex!important;flex-flow:row wrap!important;align-items:flex-start!important;justify-content:flex-start!important;gap:var(--dash5-pill-gap,0px)!important;margin:0!important;padding:4px 12px 12px!important;box-sizing:border-box!important}#root>*{flex:0 1 auto!important;max-width:min(100%,360px)!important}`]}customElements.define('dash6-pill-layout',Pills)});

customElements.whenDefined('grid-layout').then(()=>{const Base=customElements.get('grid-layout');class InlinePills extends Base{static styles=[Base.styles,css`#root{display:flex!important;flex-flow:row wrap!important;align-items:center!important;justify-content:flex-start!important;gap:8px!important;margin:0!important;padding:0!important;box-sizing:border-box!important}#root>*{flex:0 1 auto!important;width:max-content!important;min-width:0!important;max-width:100%!important;margin:0!important}`]}customElements.define('dash6-inline-pill-layout',InlinePills)});
