import './config-editor.js';
import {SWITCH_TYPES} from './glass-switch.js';
import {Base,copy,el,button,emit,loadEntityRegistry,addStyle,clamp,automaticSegments,suggestions,normalizeConfig} from './light-cards.js';
export class Dash5LightEditor extends Base {
  constructor(){super();this.attachShadow({mode:'open'});this._registry=[];this._discoverToken=0;}
  setConfig(config){this._config=normalizeConfig(config);this._config.scenes=(config.scenes||[]).map(scene=>typeof scene==='string'?{entity:scene}:copy(scene));this.render();}
  set hass(hass){const first=!this._hass;this._hass=hass;if(first||!this.shadowRoot.firstChild)this.render();else for(const form of this.shadowRoot.querySelectorAll('ha-form'))form.hass=hass;if(!this._registryPending&&!this._registryLoaded){this._registryPending=true;loadEntityRegistry(hass).then(registry=>{this._registry=registry;this._registryLoaded=true;this._registryPending=false;if(this.isConnected&&this._config)this.render();}).catch(()=>{this._registryPending=false;});}}
  change(patch){this._config={...this._config,...patch};emit(this,'config-changed',{config:copy(this._config)});}
  field(label,value,change,options={}){
    const wrap=el('label',{class:'field'},label), input=el('input',{value:value??'',type:options.type||'text',list:options.domain?'dash5-entities':null,placeholder:options.placeholder||''});
    input.addEventListener('change',()=>change(input.value));wrap.append(input);return wrap;
  }
  selectField(label,value,options,change){
    const wrap=el('label',{class:'field'},label),select=el('select');for(const item of options){const option=el('option',{value:item.value},item.label);option.selected=String(value)===String(item.value);select.append(option);}select.addEventListener('change',()=>change(select.value));wrap.append(select);return wrap;
  }
  entityField(label,value,domain,change,deviceClass,required=false){
    const schema={name:'entity',required,selector:{entity:{domain,...(deviceClass?{device_class:deviceClass}:{})}}};
    if(globalThis.customElements?.get('ha-form')){
      const form=el('ha-form');form.hass=this._hass;form.data={entity:value||''};form.schema=[schema];form.computeLabel=()=>label;form.addEventListener('value-changed',event=>{event.stopPropagation();const next=event.detail?.value?.entity;change(next||'');});return form;
    }
    return this.field(label,value,next=>change(next),{domain:Array.isArray(domain)?domain[0]:domain,placeholder:'Entity auswählen',required});
  }
  checkbox(label,value,change){const wrap=el('label',{class:'check'}), input=el('input',{type:'checkbox'});input.checked=value;input.addEventListener('change',()=>change(input.checked));wrap.append(input,document.createTextNode(label));return wrap;}
  section(title,open=false){const details=el('details',open?{open:true}:{});details.append(el('summary',{},title));return details;}
  editorSegments(){return this._config.discovery?.enabled===false?[...(this._config.segments||[])]:automaticSegments(this._config,this._hass?.states||{},this._registry||[]);}
  segmentChange(entity,patch){const segments=copy(this._config.segments||[]),index=segments.findIndex(raw=>(typeof raw==='string'?raw:raw.entity)===entity);if(index>=0){const current=typeof segments[index]==='string'?{entity:segments[index]}:segments[index];segments[index]={...current,...patch};}else segments.push({entity,...patch,auto:false});this.change({segments,segment_excludes:(this._config.segment_excludes||[]).filter(id=>id!==entity)});}
  render(){
    if(!this._config)return;const c=this._config;this.shadowRoot.replaceChildren();addStyle(this.shadowRoot);const root=el('div',{class:'editor'});this.shadowRoot.append(root);
    const list=el('datalist',{id:'dash5-entities'});for(const[id,state]of Object.entries(this._hass?.states||{}))list.append(el('option',{value:id},state.attributes.friendly_name||id));root.append(list);
    const identity=this.section('Licht und Sensoren',true);identity.append(this.entityField('Hauptlicht',c.entity,'light',value=>{const changed=value!==this._config.entity;this.change({entity:value});if(changed)queueMicrotask(()=>this.discover(true));},undefined,true),this.field('Anzeigename',c.name,value=>this.change({name:value})),this.field('Icon',c.icon,value=>this.change({icon:value})),this.field('Detailtitel',c.detail_title,value=>this.change({detail_title:value})),this.entityField('Leistungssensor',c.power_entity,'sensor',value=>this.change({power_entity:value}),'power'),this.entityField('Energiesensor',c.energy_entity,'sensor',value=>this.change({energy_entity:value}),'energy'),this.field('Bestehende Detail-Subview (optional)',c.detail_path,value=>this.change({detail_path:value}),{placeholder:'/dash-5/licht-detail'}),this.field('Spalten der Originalsteuerung',c.columns??5,value=>this.change({columns:clamp(Number(value)||5,1,10)}),{type:'number'}));root.append(identity);
    const switchPanel=this.section('Ein-/Ausschalter und Kindersicherung',true);switchPanel.append(this.selectField('Schalterart',c.switch_style||'liquid_glass',SWITCH_TYPES,value=>this.change({switch_style:value})),this.checkbox('Bedienung dieser Karte sperren',c.child_lock===true,value=>this.change({child_lock:value})),this.entityField('Kindersicherung-Entity (optional)',c.child_lock_entity,['switch','input_boolean','binary_sensor'],value=>this.change({child_lock_entity:value})));root.append(switchPanel);
    const segmentDisplay=this.section('Segmente und Darstellung',true),display=c.segment_display||{};
    segmentDisplay.append(this.checkbox('Enthaltene Lichter automatisch ermitteln',c.discovery?.enabled!==false,value=>this.change({discovery:{...c.discovery,enabled:value}})),this.selectField('Anzeigeort der Segmente',display.placement||'detail',[{value:'detail',label:'Nur in der Detailansicht (Standard)'},{value:'inline',label:'Direkt unter dem Hauptlicht'}],value=>this.change({segment_display:{...display,placement:value}})),this.selectField('Segmentdarstellung',display.style||'list',[{value:'list',label:'Liste mit einzelnen Govee-Karten'},{value:'strip',label:'Schlangenförmiger Strip'},{value:'ceiling-square',label:'Deckenlicht · quadratisch'},{value:'ceiling-round',label:'Deckenlicht · rund'}],value=>this.change({segment_display:{...display,style:value}})),this.selectField('Strip-Spalten',display.columns||'auto',[{value:'auto',label:'Automatisch nach verfügbarer Breite'},{value:'2',label:'2 pro Zeile'},{value:'3',label:'3 pro Zeile'},{value:'4',label:'4 pro Zeile'},{value:'5',label:'5 pro Zeile'},{value:'6',label:'6 pro Zeile'}],value=>this.change({segment_display:{...display,columns:value}})));
    const members=el('div',{class:'member-stack'}),visibleSegments=this.editorSegments();for(const[rawIndex,raw]of visibleSegments.entries()){
      const segment=typeof raw==='string'?{entity:raw}:raw,index=rawIndex,configured=(this._config.segments||[]).some(item=>(typeof item==='string'?item:item.entity)===segment.entity),row=el('div',{class:'member-edit'});
      row.append(el('strong',{},`${segment.name||this._hass?.states?.[segment.entity]?.attributes?.friendly_name||segment.entity||'Neues Licht'}${configured?'':' · automatisch erkannt'}`),this.entityField('Enthaltenes Licht',segment.entity,'light',value=>{if(value!==segment.entity){const segments=copy(this._config.segments||[]),oldIndex=segments.findIndex(item=>(typeof item==='string'?item:item.entity)===segment.entity),replacement={...segment,entity:value,name:this._hass?.states?.[value]?.attributes?.friendly_name||value,auto:false};if(oldIndex>=0)segments[oldIndex]=replacement;else segments.push(replacement);const excludes=new Set(this._config.segment_excludes||[]);if(segment.entity)excludes.add(segment.entity);excludes.delete(value);this.change({segments,segment_excludes:[...excludes]});this.render();}else this.segmentChange(segment.entity,{entity:value});}),this.field('Anzeigename',segment.name,value=>this.segmentChange(segment.entity,{name:value})),this.field('Icon',segment.icon,value=>this.segmentChange(segment.entity,{icon:value})));
      const extras=this.section('Leistung, Energie und Funktionen');extras.append(this.entityField('Leistungssensor',segment.power_entity,'sensor',value=>this.segmentChange(segment.entity,{power_entity:value}),'power'),this.entityField('Energiesensor',segment.energy_entity,'sensor',value=>this.segmentChange(segment.entity,{energy_entity:value}),'energy'),this.checkbox('Effekte',segment.show_effects!==false,value=>this.segmentChange(segment.entity,{show_effects:value})),this.checkbox('Farbtemperatur',segment.show_color_temp!==false,value=>this.segmentChange(segment.entity,{show_color_temp:value})));row.append(extras);
      const actions=el('div',{class:'row'}),ordered=[...visibleSegments];actions.append(button('↑',()=>{[ordered[index-1],ordered[index]]=[ordered[index],ordered[index-1]];this.change({segments:ordered});this.render();},{disabled:index===0,'aria-label':'Licht nach oben'}),button('↓',()=>{[ordered[index+1],ordered[index]]=[ordered[index],ordered[index+1]];this.change({segments:ordered});this.render();},{disabled:index===visibleSegments.length-1,'aria-label':'Licht nach unten'}),button('Entfernen',()=>{const id=segment.entity;this.change({segments:(this._config.segments||[]).filter(item=>(typeof item==='string'?item:item.entity)!==id),segment_excludes:[...new Set([...(this._config.segment_excludes||[]),id])]});this.render();}));row.append(actions);members.append(row);
    }
    const membersPanel=this.section('Enthaltene Lichter',true);membersPanel.append(members,button('Licht manuell hinzufügen',()=>{this.change({segments:[...(this._config.segments||[]),{entity:'',name:''}]});this.render();}));segmentDisplay.append(membersPanel,button('Passende Entities automatisch erkennen',()=>this.discover(true),{class:'primary'}));this._suggestions=el('div',{class:'stack',role:'status'});segmentDisplay.append(this._suggestions);root.append(segmentDisplay);
    const control=c.controls||{},controls=this.section('Regler und Bedienelemente',true);
    controls.append(this.checkbox('Reglerzeile mit Funktionsbuttons anzeigen',c.rows.controls,value=>this.change({rows:{...c.rows,controls:value}})));
    controls.append(this.selectField('Reglerdarstellung',control.mode||'combo',[{value:'combo',label:'Kombi-Regler mit Funktionsbuttons (Standard)'},{value:'separate',label:'Einzelne Regler'}],value=>this.change({controls:{...control,mode:value}})),this.selectField('Button-Beschriftung',control.label||'icon',[{value:'icon',label:'Icons (Standard)'},{value:'text',label:'Text'}],value=>this.change({controls:{...control,label:value}})),this.selectField('Button-Anordnung',control.buttons||'group',[{value:'group',label:'Gemeinsame Button-Gruppe (Standard)'},{value:'individual',label:'Einzelne Buttons'}],value=>this.change({controls:{...control,buttons:value}})),this.selectField('Button-Größe',control.density||'compact',[{value:'compact',label:'Kompakt (Standard)'},{value:'normal',label:'Normal'}],value=>this.change({controls:{...control,density:value}})),this.selectField('Position der Funktionsbuttons',control.position||'right',[{value:'right',label:'Inline rechts neben dem Regler (Standard)'},{value:'left',label:'Inline links neben dem Regler'},{value:'top',label:'Oberhalb des Reglers'},{value:'bottom',label:'Unterhalb des Reglers'}],value=>this.change({controls:{...control,position:value}})),this.checkbox('Helligkeit anzeigen, falls unterstützt',control.brightness!==false,value=>this.change({controls:{...control,brightness:value}})),this.checkbox('RGB-Farbe anzeigen, falls unterstützt',control.color!==false,value=>this.change({controls:{...control,color:value}})),this.checkbox('Weißkanal anzeigen, falls unterstützt',control.white_channels!==false,value=>this.change({controls:{...control,white_channels:value}})),this.checkbox('Effekte anzeigen, falls unterstützt',c.show_effects!==false,value=>this.change({show_effects:value})),this.checkbox('Farbtemperatur anzeigen, falls unterstützt',c.show_color_temp!==false,value=>this.change({show_color_temp:value})));
    root.append(controls);
    const toggles=c.main_back||{},togglePanel=this.section('Hauptlicht- und Backlight-Schalter');
    togglePanel.append(this.checkbox('Schalter anzeigen',toggles.enabled===true,value=>this.change({main_back:{...toggles,enabled:value}})),this.selectField('Anzeigeort',toggles.placement||'detail',[{value:'detail',label:'Nur in der Detailansicht (Standard)'},{value:'header',label:'Oben rechts im Kartenkopf'}],value=>this.change({main_back:{...toggles,placement:value}})),this.checkbox('Hauptlicht anzeigen',toggles.show_main!==false,value=>this.change({main_back:{...toggles,show_main:value}})),this.entityField('Hauptlicht-Schalter oder Ziellicht',toggles.main_entity,['light','switch'],value=>this.change({main_back:{...toggles,main_entity:value}})),this.checkbox('Backlight anzeigen',toggles.show_back!==false,value=>this.change({main_back:{...toggles,show_back:value}})),this.entityField('Backlight-Schalter oder Ziellicht',toggles.back_entity,['light','switch'],value=>this.change({main_back:{...toggles,back_entity:value}})),this.checkbox('Govee-Segmente automatisch als Haupt-/Backlight aufteilen',toggles.auto_detect!==false,value=>this.change({main_back:{...toggles,auto_detect:value}})));root.append(togglePanel);
    const graph=c.graph||{},graphPanel=this.section('Leistungsgraph und Rückmeldung');
    graphPanel.append(this.field('Mindestmaximum der Leistungsskala (W)',graph.minimum??100,value=>this.change({graph:{...graph,minimum:Math.max(1,Number(value)||100)}}),{type:'number'}));
    graphPanel.append(this.checkbox('Mini-Graph im Kartenhintergrund anzeigen, wenn ein passender Sensor gewählt ist',graph.show!==false,value=>this.change({graph:{...graph,show:value}})),this.selectField('Graph-Quelle',graph.source||'auto',[{value:'auto',label:'Automatisch · Leistung, sonst Energie'},{value:'power',label:'Leistungssensor'},{value:'energy',label:'Energiesensor'}],value=>this.change({graph:{...graph,source:value}})),this.selectField('Graph-Auflösung',graph.interval||'15min',[{value:'5min',label:'5 Minuten'},{value:'15min',label:'15 Minuten (Standard)'},{value:'30min',label:'30 Minuten'},{value:'1h',label:'1 Stunde'}],value=>this.change({graph:{...graph,interval:value}})),this.field('Graph-Zeitraum',graph.span||'24h',value=>this.change({graph:{...graph,span:value}})),this.field('Graph-Aktualisierung',graph.update_interval||'5min',value=>this.change({graph:{...graph,update_interval:value}})),this.field('Graph-Höhe in Pixeln',graph.height??80,value=>this.change({graph:{...graph,height:clamp(Number(value)||80,64,120)}}),{type:'number'}),this.checkbox('Zustand sofort darstellen',c.feedback?.optimistic!==false,value=>this.change({feedback:{...c.feedback,optimistic:value}})),this.field('Wartezeit bis Verzögerungshinweis in Sekunden',Math.round((c.feedback?.timeout_ms||60000)/1000),value=>this.change({feedback:{...c.feedback,timeout_ms:clamp(Number(value)||60,30,120)*1000}}),{type:'number'}));root.append(graphPanel);
    const scenes=el('details');scenes.append(el('summary',{},'Szenen'));scenes.append(this.checkbox('Versenkte Szenenzeile anzeigen',c.rows.scenes,value=>this.change({rows:{...c.rows,scenes:value}})));
    (c.scenes||[]).forEach((raw,index)=>{const scene=typeof raw==='string'?{entity:raw}:raw,row=el('div',{class:'member-edit'});const update=patch=>{const value=copy(this._config.scenes);value[index]={...scene,...patch};this.change({scenes:value});};row.append(this.entityField('Szene',scene.entity,'scene',value=>update({entity:value})),this.field('Name',scene.name,value=>update({name:value})),this.field('Icon',scene.icon,value=>update({icon:value})),this.field('Button-Füllung (CSS-Farbe oder Verlauf, optional)',scene.fill,value=>update({fill:value})),this.entityField('Status-Entity (optional)',scene.state_entity,'light',value=>update({state_entity:value})));row.append(button('Entfernen',()=>{this.change({scenes:this._config.scenes.filter((_,i)=>i!==index)});this.render();}));scenes.append(row);});
    scenes.append(button('Szene hinzufügen',()=>{this.change({scenes:[...(this._config.scenes||[]),{entity:'',name:''}]});this.render();}));root.append(scenes);
    root.append(this.checkbox('Ausgeblendete Entities bei Vorschlägen berücksichtigen',c.discovery?.include_hidden===true,value=>this.change({discovery:{...c.discovery,include_hidden:value}})));
    const full=this.section('Alle Einstellungen einschließlich Templates und Erweiterungen');const form=el('dash6-config-editor');form.hass=this._hass;form.setConfig(c);form.addEventListener('config-changed',e=>{e.stopPropagation();this._config=copy(e.detail.config);emit(this,'config-changed',{config:copy(this._config)});});full.append(form);root.append(full);
    root.append(el('p',{class:'muted hint'},'Vorschläge ändern keine Geräte. Bestehende Zuordnungen bleiben erhalten.'));
  }
  async discover(autoAdd=false){
    if(!this._hass){this._suggestions.textContent='Home Assistant noch nicht verfügbar.';return;}
    const token=++this._discoverToken,host=this._suggestions;if(host)host.textContent='Zuordnungen werden geprüft…';let registryAvailable=true;
    try{this._registry=await loadEntityRegistry(this._hass);}catch{registryAvailable=false;this._registry=[];}
    if(token!==this._discoverToken||!host?.isConnected)return;
    let found=suggestions(this._config,this._hass.states,this._registry);
    if(autoAdd){const certain=found.members.filter(item=>item.certain),ids=new Set((this._config.segments||[]).map(s=>typeof s==='string'?s:s.entity)),added=certain.filter(item=>!ids.has(item.entity)&&!(this._config.segment_excludes||[]).includes(item.entity));if(added.length){this.change({segments:[...(this._config.segments||[]),...added.map(({entity,name})=>({entity,name,auto:true}))]});this.render();queueMicrotask(()=>this.discover(false));return;}}
    this._suggestions.replaceChildren();
    if(!registryAvailable)this._suggestions.append(el('p',{},'Gerätezuordnung nicht zugänglich. Nur ausdrücklich gemeldete Gruppenmitglieder werden vorgeschlagen.'));
    for(const item of found.members)this._suggestions.append(button(`${item.name} · ${item.reason} · hinzufügen`,e=>{this.change({segments:[...(this._config.segments||[]),{entity:item.entity,name:item.name,auto:!item.certain}],segment_excludes:(this._config.segment_excludes||[]).filter(id=>id!==item.entity)});this.render();}));
    for(const[key,label]of [['power','Leistung'],['energy','Energie']]){
      if(this._config[key+'_entity'])continue;
      for(const id of found[key])this._suggestions.append(button(`${label}: ${this._hass.states[id].attributes.friendly_name||id}${found[key].length>1?' · mehrere Treffer':''}`,()=>{this.change({[key+'_entity']:id});this.render();}));
    }
    for(const item of found.switches){if(!item.role||this._config.main_back?.[`${item.role}_entity`])continue;const label=item.role==='main'?'Hauptlicht':'Backlight';this._suggestions.append(button(`${label}-Schalter: ${item.name} · zuordnen`,()=>{this.change({main_back:{...this._config.main_back,[`${item.role}_entity`]:item.entity,enabled:true}});this.render();}));}
    if(!found.members.length&&!found.power.length&&!found.energy.length&&!found.switches.length)this._suggestions.append(el('p',{},'Keine weiteren passenden Entities gefunden. Bestehende Zuordnungen bleiben erhalten; weitere Entities kannst du manuell auswählen.'));
  }
}

if(!customElements.get('dash6-light-card-editor-v2'))customElements.define('dash6-light-card-editor-v2',Dash5LightEditor);
