import {LitElement,html,css,unsafeCSS} from 'lit';
import BASE_CSS from './base.css';
import {buttonCSS,bindThemePreferences,unbindThemePreferences} from './material.js';
import {reportError,errorIndicator} from './error-indicator.js';
export const mediaOn=s=>!!s&&!['off','standby','unknown','unavailable'].includes(s.state);
export const mediaChoice=(states,c)=>mediaOn(states[c.apple_entity])?'apple':'fire';
export const fireCommand=(command,hold=0)=>{const map={up:19,down:20,left:21,right:22,select:23,menu:4,home:3,volume_up:24,volume_down:25,play_pause:85,previous:88,next:87,wakeup:224,suspend:223};return map[command]===undefined?null:`input keyevent ${hold?'--longpress ':''}${map[command]}`;};
const playerSurface=new CSSStyleSheet();playerSurface.replaceSync(':host{--ha-card-border-width:0px;--ha-card-box-shadow:none}ha-card{background:transparent!important;border:0!important;border-radius:0!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}.color-block,.no-img{background:transparent!important}.color-gradient{background-image:none!important}');
const compactPlayer=new CSSStyleSheet();compactPlayer.replaceSync('.top-info,.media-info{display:none!important}.player{padding-top:0!important}.title-controls{margin-top:0!important}');
export function integratePlayer(card,compact=false){const sheets=compact?[playerSurface,compactPlayer]:[playerSurface];const integrate=r=>{if(r._dash6PlayerSurface)return r;let proto=r,descriptor;while(proto&&!descriptor){descriptor=Object.getOwnPropertyDescriptor(proto,'adoptedStyleSheets');proto=Object.getPrototypeOf(proto);}if(descriptor?.get&&descriptor?.set){Object.defineProperty(r,'adoptedStyleSheets',{get:()=>descriptor.get.call(r),set:sheets=>descriptor.set.call(r,[...sheets.filter(sheet=>!([playerSurface,compactPlayer].includes(sheet))),...(compact?[playerSurface,compactPlayer]:[playerSurface])])});}r.adoptedStyleSheets=[...r.adoptedStyleSheets,...sheets];r._dash6PlayerSurface=true;return r;};if(card.shadowRoot)integrate(card.shadowRoot);if(card.createRenderRoot){const original=card.createRenderRoot.bind(card);card.createRenderRoot=()=>integrate(original());}return card;}
export const defaults={apple_entity:'media_player.example_apple_tv',apple_remote:'remote.example_apple_tv',fire_entity:'media_player.example_fire_tv',apple_device_type:'appletv-4k-gen2',fire_device_type:'fire_tv_4_series',name:'Fernseher & Apple TV'};

const DIALOG_CSS=`${buttonCSS}
.dash6-media-dialog{margin:auto;padding:0;width:min(900px,calc(100vw - 24px));max-height:calc(100dvh - 24px);color:var(--primary-text-color);background:var(--dash5-inner-background,var(--card-background-color));border:var(--dash5-inner-border);border-radius:24px;box-shadow:var(--dash5-inner-shadow);backdrop-filter:var(--dash5-inner-filter);-webkit-backdrop-filter:var(--dash5-inner-filter);overflow:auto;box-sizing:border-box}.dash6-media-dialog::backdrop{background:rgba(0,0,0,.48)}.dash6-media-dialog header{display:flex;align-items:center;justify-content:space-between;padding:16px 20px;gap:12px}.dash6-media-dialog h2{margin:0;font:600 22px/30px system-ui}.dash6-media-dialog .close{width:44px;height:44px}.dash6-media-dialog .body{display:grid;grid-template-columns:minmax(0,1fr) minmax(240px,330px);gap:16px;padding:0 20px 20px}.dash6-media-dialog .media{min-width:0}.dash6-media-dialog .device-tabs{display:flex;gap:8px;margin:0 20px 16px}.dash6-media-dialog .device-tabs button{flex:1;min-height:44px}.dash6-media-dialog .device-tabs button[aria-pressed=true]{box-shadow:var(--dash6-button-pressed-shadow);border-color:var(--primary-color)}.dash6-media-dialog .remote{display:flex;justify-content:center;min-width:0}.dash6-media-dialog .remote>*{max-width:100%;width:280px}.dash6-media-dialog .hint{color:var(--secondary-text-color);font:13px/1.5 system-ui}.dash6-media-dialog .transport{display:flex;gap:8px;margin-top:12px}.dash6-media-dialog .transport button{flex:1;min-height:44px}.dash6-media-dialog .fallback{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.dash6-media-dialog .fallback button{min-height:48px}@media(max-width:600px){.dash6-media-dialog .body{grid-template-columns:1fr;padding:0 12px 12px}.dash6-media-dialog .remote{min-height:0}.dash6-media-dialog .device-tabs{margin-inline:12px}}
`;
class MediaCard extends LitElement{
 static properties={hass:{attribute:false},_native:{state:true}};
 static styles=[unsafeCSS(BASE_CSS),unsafeCSS(buttonCSS),css`:host{display:block;min-width:0}ha-card{overflow:hidden;background:var(--dash5-inner-background);border:var(--dash5-inner-border);border-radius:var(--dash5-card-radius,16px)!important;box-shadow:var(--dash5-inner-shadow);backdrop-filter:var(--dash5-inner-filter);-webkit-backdrop-filter:var(--dash5-inner-filter)}.head{display:flex;align-items:center;gap:12px;padding:12px;cursor:pointer}.head{background:transparent!important;border:0!important;border-radius:0!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;transform:none!important}.head:focus-visible{outline:2px solid var(--primary-color);outline-offset:-3px}.head ha-icon{width:44px;height:44px;display:grid;place-items:center;flex:none;border-radius:var(--dash6-icon-lens-radius,14px);background:var(--dash6-icon-lens-background);border:var(--dash6-icon-lens-border);box-shadow:var(--dash6-icon-lens-shadow);box-sizing:border-box}.title{font-size:16px;font-weight:600}.state{font-size:13px;color:var(--secondary-text-color)}.player{margin:0 12px 12px;min-width:0}.footer{display:flex;gap:8px;padding:0 12px 12px}.footer button{flex:1;min-height:44px}`];
 static async getConfigElement(){await import('./media-editor.js');return document.createElement('dash6-media-editor');}
 static getStubConfig(){return {type:'custom:dash6-media-card',...defaults};}
 setConfig(c){this._config={...defaults,...c};this._nativeId=null;this.requestUpdate();}
 connectedCallback(){super.connectedCallback();bindThemePreferences(this);}
 disconnectedCallback(){this.close();unbindThemePreferences(this);super.disconnectedCallback();}
 getCardSize(){return 5;}
 async updated(){if(!this.hass)return;const mode=mediaChoice(this.hass.states,this._config),id=this._config[mode+'_entity'];if(id!==this._nativeId){this._nativeId=id;const helper=await window.loadCardHelpers();const card=await helper.createCardElement({type:'media-control',entity:id});if(this._nativeId!==id)return;if(card.localName.includes('-')){await customElements.whenDefined(card.localName);customElements.upgrade(card);}integratePlayer(card,true);card.hass=this.hass;this._native=card;}else if(this._native)this._native.hass=this.hass;if(this._dialog)this.updateDialog();}
 async send(command,hold=0){try{if(this._selected==='fire'){const adb=fireCommand(command,hold);if(adb)await this.hass.callService('androidtv','adb_command',{entity_id:this._config.fire_entity,command:adb});}else await this.hass.callService('remote','send_command',{entity_id:this._config.apple_remote,command:command==='play_pause'?'play_pause':command,hold_secs:hold});}catch(e){reportError(this,e.message||String(e));}}
 close(){clearTimeout(this._hold);window.removeEventListener('keydown',this._keyDown,true);window.removeEventListener('keyup',this._keyUp,true);window.removeEventListener('blur',this._blur);window.removeEventListener('location-changed',this._location);this._dialog?.close();this._dialog?.remove();this._dialog=null;this._remoteCards=null;this._dialogPlayers=null;}
 async open(){try{await this.openDialog();}catch(e){this.close();reportError(this,e.message||String(e));}}
 async openDialog(){if(this._dialog)return;this._selected=mediaChoice(this.hass.states,this._config);this._remoteCards={};this._dialogPlayers={};const d=document.createElement('dialog');this._dialog=d;d.className='dash6-media-dialog';d.setAttribute('aria-label','Fernseher und Apple TV');d.innerHTML=`<style>${DIALOG_CSS}</style><header><h2>Fernseher & Apple TV</h2><button class="close" aria-label="Schließen">✕</button></header><div class="device-tabs" role="group" aria-label="Fernbedienung wählen"><button data-device="apple">Apple TV</button><button data-device="fire">Fire TV / Fernseher</button></div><div class="body"><section class="media"><div class="player-slot"></div><div class="transport"><button data-cmd="wakeup">Aufwecken</button><button data-cmd="suspend">Ruhezustand</button></div><p class="hint">Pfeiltasten · Enter: OK · Rückschritt/Entf: Zurück · +/−: Lautstärke · Leertaste: Play/Pause · #: Home (lang halten für Home-Menü). Tastatursteuerung gilt nur in diesem Overlay und für die ausgewählte Fernbedienung.</p></section><section class="remote" aria-label="Fernbedienung"></section></div>`;
 d.querySelector('.close').onclick=()=>this.close();d.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{clearTimeout(this._hold);this._selected=b.dataset.device;this.updateDialog();});d.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>this.send(b.dataset.cmd));d.addEventListener('cancel',e=>{e.preventDefault();this.close();});d.onclick=e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)this.close();}};
 d.addEventListener('hass-more-info',e=>{e.stopPropagation();const detail=e.detail;this.close();document.querySelector('home-assistant').dispatchEvent(new CustomEvent('hass-more-info',{detail,bubbles:true,composed:true}));});document.body.append(d);d.showModal();
 this._keyDown=e=>{if(!d.matches(':modal')||e.repeat||e.metaKey||e.ctrlKey||e.altKey||e.composedPath().some(x=>['INPUT','TEXTAREA','SELECT'].includes(x.tagName)||x.isContentEditable))return;if(['Enter',' '].includes(e.key)&&e.composedPath().some(x=>x.tagName==='BUTTON'))return;const cmd={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',Enter:'select',Backspace:'menu',Delete:'menu','+':'volume_up','-':'volume_down',' ':'play_pause'}[e.key];if(!cmd&&e.key!=='#')return;e.preventDefault();e.stopImmediatePropagation();if(e.key==='#'){this._long=false;this._hold=setTimeout(()=>{this._long=true;this.send('home',1)},450);}else this.send(cmd);};
 this._keyUp=e=>{if(e.key==='#'&&this._hold){e.preventDefault();e.stopImmediatePropagation();clearTimeout(this._hold);this._hold=null;if(!this._long)this.send('home');}};this._blur=()=>{clearTimeout(this._hold);this._hold=null;};this._location=()=>this.close();window.addEventListener('keydown',this._keyDown,true);window.addEventListener('keyup',this._keyUp,true);window.addEventListener('blur',this._blur);window.addEventListener('location-changed',this._location);
 const helpers=await window.loadCardHelpers();if(!customElements.get('firemote-card')){d.querySelector('.remote').textContent='Fernbedienung wird geladen …';try{await import(/* @vite-ignore */ '/local/liquid-glass/vendor/firemote/HA-Firemote.js?hacstag=536329656419');}catch(error){console.warn('DASH6 Firemote: Ersatzsteuerung wird verwendet',error.message);}if(this._dialog!==d)return;}for(const mode of ['apple','fire']){const entity=this._config[mode+'_entity'];const player=await helpers.createCardElement({type:'media-control',entity});if(player.localName.includes('-')){await customElements.whenDefined(player.localName);customElements.upgrade(player);}integratePlayer(player);let remote;if(customElements.get('firemote-card'))remote=await helpers.createCardElement({type:'custom:firemote-card',entity,device_family:mode==='apple'?'apple-tv':'amazon-fire',device_type:this._config[mode+'_device_type'],compatibility_mode:'default',...(mode==='apple'?{apple_tv_remote_entity:this._config.apple_remote}:{}),scale:70});else{remote=document.createElement('div');remote.className='fallback';for(const [label,cmd] of [['↑','up'],['Home','home'],['Zurück','menu'],['←','left'],['OK','select'],['→','right'],['−','volume_down'],['↓','down'],['+','volume_up'],['Play/Pause','play_pause']]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>this.send(cmd);remote.append(b);}}if(this._dialog!==d)return;this._dialogPlayers[mode]=player;this._remoteCards[mode]=remote;}
 this.updateDialog();
 }
 updateDialog(){const d=this._dialog;if(!d)return;for(const card of [...Object.values(this._dialogPlayers||{}),...Object.values(this._remoteCards||{})])card.hass=this.hass;d.querySelectorAll('[data-device]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.device===this._selected)));const remote=this._remoteCards?.[this._selected],player=this._dialogPlayers?.[this._selected];if(remote&&d.querySelector('.remote').firstChild!==remote)d.querySelector('.remote').replaceChildren(remote);if(player&&d.querySelector('.player-slot').firstChild!==player)d.querySelector('.player-slot').replaceChildren(player);}
 render(){if(!this.hass)return html``;const selected=mediaChoice(this.hass.states,this._config),s=this.hass.states[this._config[selected+'_entity']];return html`<ha-card><div class="head detail-link" role="button" tabindex="0" aria-label="Fernseher und Apple TV öffnen" @click=${()=>this.open()} @keydown=${e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();this.open()}}}><ha-icon .icon=${selected==='apple'?'mdi:apple':'mdi:television'}></ha-icon><div><div class="title">${this._config.name}</div><div class="state">${selected==='apple'?'Apple TV':'Fire TV'} · ${s?this.hass.formatEntityState(s):'Nicht verfügbar'}${s?.attributes?.media_title?' · '+s.attributes.media_title:''}</div></div>${errorIndicator(this)}</div><div class="player">${this._native}</div><div class="footer"><button @click=${()=>this.open()}>Fernbedienungen</button></div></ha-card>`;}
}
customElements.define('dash6-media-card',MediaCard);window.customCards??=[];window.customCards.push({type:'dash6-media-card',name:'DASH6 Fernseher & Apple TV',description:'Automatische Medienkarte mit umschaltbaren Firemote-Fernbedienungen und Tastatursteuerung.',preview:true});
