import {displacementPixels} from './displacement-map.js';
import {LitElement,html,svg,css} from 'lit';
import {surface,} from './material.js';
let sequence=0;
export function displacementURL(){
 const canvas=document.createElement('canvas');canvas.width=128;canvas.height=128;const ctx=canvas.getContext('2d');if(!ctx)return '';const data=ctx.createImageData(128,128);data.data.set(displacementPixels());ctx.putImageData(data,0,0);return canvas.toDataURL('image/png');
}
// Safari can displace SVG SourceGraphic. This filters a second render of the
// controlled scene, not an unsupported backdrop-filter URL or a foreignObject.
export function railLens(target,index,count){
 if(!target._refraction){const map=displacementURL();if(!map)return;const id='dash6-rail-'+(++sequence);const ns='http://www.w3.org/2000/svg';const s=document.createElementNS(ns,'svg');s.setAttribute('viewBox','0 0 120 80');s.setAttribute('preserveAspectRatio','none');s.setAttribute('aria-hidden','true');s.style.cssText='position:absolute;inset:0;width:100%;height:100%;border-radius:inherit;overflow:hidden;pointer-events:none';s.innerHTML=`<defs><filter id="${id}" x="-25%" y="-25%" width="150%" height="150%" color-interpolation-filters="sRGB"><feImage href="${map}" x="0" y="0" width="120" height="80" preserveAspectRatio="none" result="map"/><feDisplacementMap in="SourceGraphic" in2="map" scale="14" xChannelSelector="R" yChannelSelector="G"/></filter><linearGradient id="${id}-color" x2="0" y2="1"><stop stop-color="var(--dash6-segment-rail-color,#087aff)"/><stop offset="1" stop-color="var(--dash6-segment-rail-dark,#0043bd)"/></linearGradient></defs><g filter="url(#${id})"><rect x="-15" y="14" width="150" height="52" rx="26" fill="url(#${id}-color)"/><path d="M-15 17H140 M-15 63H140" stroke="white" stroke-opacity=".25" fill="none"/></g>`;target.prepend(s);target._refraction=s;}
 target._refraction.dataset.index=String(index);target._refraction.dataset.count=String(count);
}
class RefractionCard extends LitElement {
 static properties={hass:{attribute:false},_config:{state:true},_selected:{state:true}};
 static styles=css`:host{display:block}ha-card{display:block;overflow:hidden;padding:16px;border-radius:16px;background:var(--dash5-inner-background);border:var(--dash5-inner-border);color:var(--primary-text-color)}h3{margin:0 0 8px}p{font-size:13px;line-height:1.4;color:var(--secondary-text-color)}svg{width:100%;height:auto;display:block;border-radius:18px}button{min-height:44px;border-radius:22px;border:var(--dash6-segment-selected-border);background:var(--dash6-segment-selected);color:var(--primary-text-color);padding:8px 16px;font:inherit}`;
 constructor(){super();this._id='dash6-scene-'+(++sequence);this._selected=0;}
 static getConfigElement(){const e=document.createElement('dash6-basic-editor');e.schema=[{name:'name',label:'Titel',selector:{text:{}}},{name:'strength',label:'Brechungsstärke',selector:{number:{min:0,max:24,step:1,mode:'slider'}}}];return e;}
 static getStubConfig(){return {type:'custom:dash6-refraction-card',name:'Safari SVG-Linsen',strength:14};}
 setConfig(c){this._config=c;}
 connectedCallback(){super.connectedCallback();try{this._map=displacementURL();}catch{this._map='';}}
 getCardSize(){return 4;}
 render(){if(!this._config)return html``;const id=this._id,x=[68,230,392][this._selected],lenses=[{x,y:26,w:140,h:94,r:44},{x:67,y:182,w:96,h:96,r:48},{x:230,y:166,w:290,h:116,r:28}],scale=Math.max(0,Math.min(24,Number(this._config.strength??14)));return html`<ha-card><h3>${this._config.name||'Safari SVG-Linsen'}</h3><svg viewBox="0 0 600 310" role="img" aria-label="Vergleich einer unverzerrten Szene mit SVG-Glaslinsen"><defs><linearGradient id=${id+'-bg'}><stop stop-color="#236283"/><stop offset=".5" stop-color="#6a48b6"/><stop offset="1" stop-color="#164449"/></linearGradient><pattern id=${id+'-grid'} width="24" height="24" patternUnits="userSpaceOnUse"><path d="M24 0H0V24" stroke="white" stroke-opacity=".6" fill="none"/></pattern>${lenses.map((l,i)=>svg`<filter id=${id+'-filter-'+i} filterUnits="userSpaceOnUse" x=${l.x-24} y=${l.y-24} width=${l.w+48} height=${l.h+48} color-interpolation-filters="sRGB"><feImage href=${this._map} x=${l.x} y=${l.y} width=${l.w} height=${l.h} preserveAspectRatio="none" result="map"/><feDisplacementMap in="SourceGraphic" in2="map" scale=${scale} xChannelSelector="R" yChannelSelector="G"/></filter><clipPath id=${id+'-clip-'+i}><rect x=${l.x} y=${l.y} width=${l.w} height=${l.h} rx=${l.r}/></clipPath>`)}<g id=${id+'-scene'}><rect width="600" height="310" fill=${'url(#'+id+'-bg)'}/><rect width="600" height="310" fill=${'url(#'+id+'-grid)'}/><path d="M0 40L600 270M0 250L600 60" stroke="#ffc56e" stroke-width="9"/><rect x="40" y="48" width="520" height="50" rx="25" fill="#087aff"/></g></defs><use href=${'#'+id+'-scene'}/>${lenses.map((l,i)=>svg`<g clip-path=${'url(#'+id+'-clip-'+i+')'}><use href=${'#'+id+'-scene'} filter=${'url(#'+id+'-filter-'+i+')'}/><rect x=${l.x} y=${l.y} width=${l.w} height=${l.h} fill="white" fill-opacity=".09"/></g>`)}<rect x=${x} y="26" width="140" height="94" rx="44" fill="none" stroke="white" stroke-opacity=".8" stroke-width="2"/><circle cx="115" cy="230" r="48" fill="none" stroke="white" stroke-opacity=".8" stroke-width="2"/><rect x="230" y="166" width="290" height="116" rx="28" fill="none" stroke="white" stroke-opacity=".8" stroke-width="2"/></svg><button @click=${()=>this._selected=(this._selected+1)%3}>Linse verschieben</button><p>SVG-Displacement auf einer zweiten Darstellung derselben Szene: Button, rundes Icon und Glasfläche. Das Raster macht die Brechung sichtbar. Kein SVG-Filter auf dem Live-Backdrop.</p>${!this._map?html`<p role="status">Displacement-Map nicht verfügbar.</p>`:''}</ha-card>`;}
}
customElements.define('dash6-refraction-card',RefractionCard);window.customCards??=[];window.customCards.push({type:'dash6-refraction-card',name:'DASH6 Safari SVG-Linsen',description:'Safari-Test mit echter SVG-Verzerrung einer kontrollierten Szenenkopie.',preview:true});
