import './config-editor.js';
import {bindThemePreferences,unbindThemePreferences} from './material.js';
import {bindSatinMode} from './satin-surface.js';
import {railLens} from './refraction.js';
import {LitElement, html, css, unsafeCSS} from 'lit';
import {surface} from './material.js';
// The track and buttons retain their identity when selection or HA state changes.
export class GlassSegments extends HTMLElement {
 constructor(){super();this.attachShadow({mode:'open'});this.shadowRoot.innerHTML=`<style>
 :host{display:block;min-width:0;--count:3} .group{width:100%;box-sizing:border-box;position:relative;display:grid;grid-template-columns:repeat(var(--count),minmax(0,1fr));padding:3px;border-radius:26px;isolation:isolate;background:var(--dash6-segment-background,var(--dash6-control-background));border:var(--dash6-segment-border,1px solid var(--divider-color));box-shadow:var(--dash6-segment-shadow);backdrop-filter:var(--dash6-segment-filter);-webkit-backdrop-filter:var(--dash6-segment-filter)}
 .track{position:absolute;left:3px;top:var(--dash6-segment-lens-top,-5px);bottom:var(--dash6-segment-lens-top,-5px);width:calc((100% - 6px)/var(--count));pointer-events:none;transition:transform var(--dash6-segment-duration,300ms) cubic-bezier(.22,.8,.25,1);z-index:0}
 .glass{height:100%;position:relative;border-radius:var(--dash6-segment-lens-radius,24px);background:var(--dash6-segment-selected,var(--dash6-control-selected));border:var(--dash6-segment-selected-border,1px solid var(--divider-color));box-sizing:border-box;box-shadow:var(--dash6-segment-selected-shadow);}
 .glass::after{content:"";position:absolute;inset:0;border-radius:inherit;pointer-events:none;background:var(--dash6-segment-lens-gloss);box-shadow:var(--dash6-segment-lens-edge)}
 .moving .glass{animation:settle var(--dash6-segment-duration,300ms) ease-out} @keyframes settle{40%{transform:scaleX(var(--dash6-segment-stretch,1.06)) scaleY(.96)}100%{transform:scale(1)}}
 button{position:relative;z-index:1;min-width:0;min-height:44px;border:0;border-radius:21px;background:transparent;color:var(--secondary-text-color);font:inherit;padding:8px 12px;cursor:pointer;display:flex;gap:6px;align-items:center;justify-content:center;-webkit-tap-highlight-color:transparent;touch-action:manipulation}
 button{transition:scale var(--dash6-button-duration,320ms) cubic-bezier(.22,1.5,.36,1),translate var(--dash6-button-duration,320ms) cubic-bezier(.22,1.5,.36,1)}button:active:not(:disabled){scale:var(--dash6-button-press-scale,.94);translate:0 var(--dash6-button-press-depth,2px)}.group:has(button:active:not(:disabled)) .glass{scale:var(--dash6-button-press-scale,.94);translate:0 var(--dash6-button-press-depth,2px)}.glass{transition:scale var(--dash6-button-duration,320ms) cubic-bezier(.22,1.5,.36,1),translate var(--dash6-button-duration,320ms) cubic-bezier(.22,1.5,.36,1)}button[aria-checked=true]{color:var(--primary-text-color);font-weight:600}button:disabled{opacity:.35;cursor:default}button:focus-visible{outline:2px solid var(--primary-color);outline-offset:-3px}ha-icon{--mdc-icon-size:20px;flex:none}span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
 :host([icons-only]) button{padding:8px;min-width:44px}:host([motion=off]) .track{transition:none}:host([motion=off]) .glass{animation:none}
 :host([data-satin]) .group{height:42px;grid-template-rows:minmax(0,1fr);align-items:center;border-radius:var(--dash6-satin-segment-radius,10px);background:var(--dash6-satin-control-background,linear-gradient(145deg,rgba(10,15,19,.3),rgba(32,39,45,.25)));border:var(--dash6-satin-control-border,1px solid rgba(255,255,255,.14));box-shadow:var(--dash6-satin-control-shadow,inset 0 2px 3px rgba(0,0,0,.34),inset 0 -1px 1px rgba(255,255,255,.045));backdrop-filter:var(--dash6-satin-control-filter,blur(9px));-webkit-backdrop-filter:var(--dash6-satin-control-filter,blur(9px));overflow:hidden}
 :host([data-satin]) .track{top:2px;bottom:2px;transition:transform var(--dash6-satin-segment-duration,380ms) cubic-bezier(.22,1.08,.36,1)}
 :host([data-satin]) .glass{border-radius:var(--dash6-satin-segment-lens-radius,8px);background:var(--dash6-satin-lens-background,linear-gradient(145deg,rgba(255,255,255,.16),rgba(255,255,255,.04)));border:var(--dash6-satin-lens-border,1px solid rgba(255,255,255,.27));box-shadow:var(--dash6-satin-lens-shadow,inset 0 1px 2px rgba(255,255,255,.13),inset 0 -1px 2px rgba(0,0,0,.17));transition:scale var(--dash6-satin-elastic-duration,380ms) cubic-bezier(.22,1.5,.36,1),translate 120ms ease,box-shadow 120ms ease}
 :host([data-satin]) .glass::after{background:var(--dash6-satin-lens-gloss,linear-gradient(145deg,rgba(255,255,255,.14),transparent 58%));box-shadow:none}
 :host([data-satin]) button{border-radius:8px;min-height:34px;height:34px;padding:4px 8px}
 :host([data-satin][icons-only]) button{padding:4px 8px}
 :host([data-satin]) button:active:not(:disabled){scale:1;translate:0 0}
 @media(hover:hover){:host([data-satin]) .group:has(button[aria-checked=true]:hover:not(:disabled)) .glass{scale:var(--dash6-satin-segment-hover-scale,1.035)}}
 :host([data-satin]) .group:has(button:active:not(:disabled)) .glass{scale:var(--dash6-satin-segment-press-scale,.975);translate:0 1px;box-shadow:var(--dash6-satin-segment-pressed-shadow,inset 0 2px 4px rgba(0,0,0,.4),inset 0 -1px 1px rgba(255,255,255,.04))}
 :host([data-satin]) .moving .glass{animation:dash6-satin-settle var(--dash6-satin-segment-duration,380ms) ease-out}
 @keyframes dash6-satin-settle{35%{transform:scaleX(1.025) scaleY(.975)}100%{transform:scale(1)}}
 :host([data-satin][motion=off]) .track,:host([data-satin][motion=off]) .glass{transition:none;animation:none;scale:1;translate:0 0}
 @media(pointer:coarse){:host([data-satin]) .group{height:44px}:host([data-satin]) button{min-height:44px;height:44px}}
 @media(prefers-reduced-motion:reduce){.track{transition:none!important}.glass{animation:none!important;scale:1!important;translate:0!important}button{transition:none!important;scale:1!important;translate:0!important}}
 @supports not ((backdrop-filter:blur(1px)) or (-webkit-backdrop-filter:blur(1px))){.group{background:var(--dash6-solid-surface,#1b2735)}}
 </style><div class="group" role="radiogroup"><div class="track" aria-hidden="true"><div class="glass"></div></div></div>`;
 this.group=this.shadowRoot.querySelector('.group');this.track=this.shadowRoot.querySelector('.track');
 }
 connectedCallback(){bindThemePreferences(this);bindSatinMode(this,()=>this.update());}
 disconnectedCallback(){unbindThemePreferences(this);}
 configure({options,value,label='Auswahl',iconsOnly=false,motion='theme',disabled=false}){
 this.options=options;this.disabled=disabled;this.setAttribute('motion',motion);this.toggleAttribute('icons-only',iconsOnly);this.group.setAttribute('aria-label',label);this.style.setProperty('--count',String(options.length||1));
 const signature=JSON.stringify([options,iconsOnly]);
 if(signature!==this.signature){this.signature=signature;this.group.querySelectorAll('button').forEach(b=>b.remove());for(const option of options){const b=document.createElement('button');b.type='button';b.setAttribute('role','radio');b.setAttribute('aria-label',option.label||option.value);b.title=option.label||option.value;if(option.icon){const icon=document.createElement('ha-icon');icon.setAttribute('icon',option.icon);b.append(icon);}if(!iconsOnly||!option.icon){const text=document.createElement('span');text.textContent=option.label||option.value;b.append(text);}b.addEventListener('click',e=>{e.stopPropagation();this.select(option.value);});b.addEventListener('keydown',e=>this.key(e,option.value));this.group.append(b);}}
 this.value=options.some(o=>o.value===value&&!o.disabled)?value:options.find(o=>!o.disabled)?.value||options[0]?.value;this.update();
 }
 update(){if(!this.options)return;const i=Math.max(0,this.options.findIndex(o=>o.value===this.value));this.track.style.transform=`translateX(${i*100}%)`;const glass=this.track.firstElementChild;if(!this.hasAttribute('data-satin')&&getComputedStyle(this).getPropertyValue('--dash6-svg-refraction').trim()==='1'){railLens(glass,i,this.options.length);}else if(glass._refraction){glass._refraction.remove();glass._refraction=null;}[...this.group.querySelectorAll('button')].forEach((b,n)=>{const selected=this.options[n].value===this.value;b.setAttribute('aria-checked',String(selected));b.tabIndex=selected?0:-1;b.disabled=this.disabled||Boolean(this.options[n].disabled);});}
 select(value){if(this.disabled||!this.options.some(o=>o.value===value&&!o.disabled)||value===this.value)return;this.value=value;this.update();this.track.classList.remove('moving');void this.track.offsetWidth;this.track.classList.add('moving');this.dispatchEvent(new CustomEvent('selection-changed',{detail:{value},bubbles:true,composed:true}));}
 key(e,value){const opts=this.options.filter(o=>!o.disabled);if(this.disabled||!opts.length)return;let i=opts.findIndex(o=>o.value===value);if(['ArrowRight','ArrowDown','ArrowLeft','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();if(e.key==='Home')i=0;else if(e.key==='End')i=opts.length-1;else i=(i+(['ArrowRight','ArrowDown'].includes(e.key)?1:-1)+opts.length)%opts.length;this.select(opts[i]?.value);[...this.group.querySelectorAll('button')].find(b=>b.getAttribute('aria-checked')==='true')?.focus();}}
}
customElements.define('dash6-glass-segments',GlassSegments);
export class SegmentedCard extends LitElement {
 static properties={hass:{attribute:false},_config:{state:true},_value:{state:true},_pending:{state:true},_error:{state:true}};
 static styles=[css`:host{display:block}ha-card{padding:12px}h3{margin:0 0 8px;font-size:16px}p{margin:8px 0 0}dash6-glass-segments{width:100%}` ,unsafeCSS(surface)];
 static getConfigElement(){return document.createElement('dash6-segmented-control-editor');}
 static getStubConfig(){return {type:'custom:dash6-segmented-control-card',name:'Auswahl',options:[{value:'eins',label:'Eins'},{value:'zwei',label:'Zwei'},{value:'drei',label:'Drei'}],default:'eins'};}
 setConfig(c){if(c.entity&&!/^(input_select|select)\./.test(c.entity))throw Error('Nur select oder input_select verwenden.');const opts=c.options||[];if(!c.entity&&!opts.length)throw Error('Mindestens eine Option erforderlich.');if(opts.some(o=>!o.value)||new Set(opts.map(o=>o.value)).size!==opts.length)throw Error('Optionen benötigen eindeutige Werte.');this._config=structuredClone(c);this._value=c.default||opts[0]?.value;}
 disconnectedCallback(){super.disconnectedCallback();clearTimeout(this._confirmTimer);this._optimisticValue=undefined;}
 getCardSize(){return 1;}
 options(){const s=this.hass?.states[this._config.entity];return this._config.entity?(s?.attributes.options||[]).map(value=>({value,...(this._config.options||[]).find(o=>o.value===value)})):this._config.options;}
 async choose(e){const value=e.detail.value,previous=this._value;this._value=value;this._error='';if(!this._config.entity)return;this._previousState=this.hass?.states[this._config.entity]?.state;this._optimisticValue=value;this._pending=true;try{await this.hass.callService(this._config.entity.split('.')[0],'select_option',{entity_id:this._config.entity,option:value});}catch(error){this._optimisticValue=undefined;this._value=previous;this._error=error.message||'Auswahl fehlgeschlagen';}finally{this._pending=false;clearTimeout(this._confirmTimer);this._confirmTimer=setTimeout(()=>{this._optimisticValue=undefined;this.requestUpdate();},5000);}}
 updated(){const c=this._config;if(!c)return;const state=this.hass?.states[c.entity],options=this.options();if(this._optimisticValue!==undefined&&(state?.state===this._optimisticValue||state?.state!==this._previousState)){this._optimisticValue=undefined;clearTimeout(this._confirmTimer);}const value=this._optimisticValue??(c.entity?state?.state:this._value);this._segments=this.shadowRoot.querySelector('dash6-glass-segments');if(this._segments){this._segments.configure({options,value,label:c.name||'Auswahl',iconsOnly:c.label==='icon',motion:c.animation===false?'off':'theme',disabled:!!c.entity&&(!state||['unknown','unavailable'].includes(state.state)||this._pending)});if(!this._pending)this._value=this._segments.value;}}
 render(){if(!this._config)return html``;return html`<ha-card>${this._config.name?html`<h3>${this._config.name}</h3>`:''}<dash6-glass-segments @selection-changed=${this.choose}></dash6-glass-segments>${this._error?html`<p role="alert">${this._error}</p>`:''}${this._config.entity&&!this.options().length?html`<p role="status">Keine verfügbaren Optionen.</p>`:''}</ha-card>`;}
}
customElements.define('dash6-segmented-control-card',SegmentedCard);
class SegmentEditor extends LitElement {
 static properties={hass:{attribute:false},_config:{state:true}};
 static styles=css`label{display:grid;gap:4px;margin:8px 0}input{min-height:36px;font:inherit}fieldset{margin:12px 0;padding:12px;border:1px solid var(--divider-color);border-radius:12px}button{min-height:40px}ha-form{display:block}`;
 setConfig(c){this._config=structuredClone(c);}
 change(p){this._config={...this._config,...p};this.dispatchEvent(new CustomEvent('config-changed',{detail:{config:structuredClone(this._config)},bubbles:true,composed:true}));}
 option(i,key,value){const options=structuredClone(this._config.options||[]);options[i][key]=value;this.change({options});}
 render(){const c=this._config;if(!c)return html``;return html`<ha-form .hass=${this.hass} .data=${{animation:true,...c}} .schema=${[{name:'name',label:'Titel',selector:{text:{}}},{name:'entity',label:'Auswahl-Entity (optional)',selector:{entity:{domain:['select','input_select']}}},{name:'default',label:'Startauswahl ohne Entity',selector:{text:{}}},{name:'label',label:'Beschriftung',selector:{select:{options:[{value:'text',label:'Text und Icon'},{value:'icon',label:'Nur Icons'}]}}},{name:'animation',label:'Animation (reduzierte Bewegung hat Vorrang)',selector:{boolean:{}}}]} .computeLabel=${s=>s.label} @value-changed=${e=>{e.stopPropagation();this.change(e.detail.value);}}></ha-form><p>Bei einer Auswahl-Entity werden deren Optionen dynamisch geladen. Die folgenden Einträge ergänzen Labels und Icons.</p>${(c.options||[]).map((o,i)=>html`<fieldset><label>Wert<input .value=${o.value||''} @change=${e=>this.option(i,'value',e.target.value)}></label><label>Beschriftung<input .value=${o.label||''} @change=${e=>this.option(i,'label',e.target.value)}></label><label>Icon<input .value=${o.icon||''} placeholder="mdi:lightbulb" @change=${e=>this.option(i,'icon',e.target.value)}></label><button @click=${()=>this.change({options:c.options.filter((_,n)=>i!==n)})}>Entfernen</button></fieldset>`)}<button @click=${()=>this.change({options:[...(c.options||[]),{value:'option'+((c.options||[]).length+1),label:'Neue Option'}]})}>Option hinzufügen</button><details><summary>Alle Einstellungen</summary><dash6-config-editor .hass=${this.hass} ._config=${c} @config-changed=${e=>{e.stopPropagation();this._config=structuredClone(e.detail.config);this.dispatchEvent(new CustomEvent('config-changed',{detail:{config:this._config},bubbles:true,composed:true}));}}></dash6-config-editor></details>`;}
}
customElements.define('dash6-segmented-control-editor',SegmentEditor);
window.customCards=window.customCards||[];window.customCards.push({type:'dash6-segmented-control-card',name:'DASH6 Liquid Glass Auswahl',description:'Animierte exklusive Auswahl; dynamisch mit select/input_select oder lokal.',preview:true});
