import {errorIndicator,reportError} from './error-indicator.js';
import {bindThemePreferences,unbindThemePreferences} from './material.js';
import {LitElement,html,css} from 'lit';
import {surface} from './material.js';
class ThermostatCard extends LitElement {
 static properties={hass:{attribute:false},_native:{state:true},_error:{state:true},_selectedMode:{state:true},_modePending:{state:true},_presetMenu:{state:true},_presetBusy:{state:true}};
 static styles=css`:host{display:block;height:265px;min-height:265px;max-height:265px}ha-card{overflow:hidden;border-radius:16px!important;height:265px;min-height:265px;max-height:265px}.features{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:0 12px 12px}.modes{display:flex;gap:0;border:var(--dash5-icon-border);border-radius:13px;overflow:hidden;background:var(--dash6-control-background);box-shadow:var(--dash5-icon-shadow)}.modes button{width:44px;height:44px;min-width:0;padding:0;border:0;color:var(--primary-text-color);background:transparent;cursor:pointer}.modes button[aria-checked=true]{background:var(--dash6-control-selected)}.modes button:focus-visible{outline:2px solid var(--primary-color);outline-offset:-2px}ha-control-select-menu{width:44px;min-height:44px;--control-select-menu-border-radius:13px;--control-select-menu-background:var(--dash6-control-background);--control-select-menu-color:var(--primary-text-color)}.preset-button{height:42px;width:44px;min-width:44px;padding:0;border:var(--dash6-button-border);border-radius:14px;background:var(--dash6-button-background);box-shadow:var(--dash6-button-shadow);color:var(--primary-text-color);backdrop-filter:var(--dash6-button-filter);-webkit-backdrop-filter:var(--dash6-button-filter);cursor:pointer;transition:scale 240ms cubic-bezier(.22,1.5,.36,1)}.preset-button:active{scale:.94;box-shadow:var(--dash6-button-pressed-shadow)}dialog{box-sizing:border-box;position:fixed;margin:0;padding:6px;min-width:190px;max-width:calc(100vw - 24px);border:var(--dash6-button-border);border-radius:14px;background:var(--dash6-tooltip-background);color:var(--primary-text-color);box-shadow:var(--dash6-tooltip-shadow);backdrop-filter:var(--dash5-inner-filter);-webkit-backdrop-filter:var(--dash5-inner-filter);z-index:20}dialog::backdrop{background:transparent}dialog button{display:flex;align-items:center;gap:10px;min-height:40px;width:100%;padding:8px 12px;border:0;border-radius:8px;background:transparent;color:inherit;text-align:left;cursor:pointer}dialog button:hover,dialog button:focus-visible{background:rgba(255,255,255,.12);outline:none}dialog button[aria-checked=true]{background:rgba(255,255,255,.08)}dialog .check{width:18px}`;
 static getConfigElement(){const e=document.createElement('dash6-basic-editor');e.schema=[{name:'entity',label:'Thermostat',required:true,selector:{entity:{domain:'climate'}}},{name:'modes',label:'Angezeigte Betriebsmodi',selector:{select:{multiple:true,options:['off','heat','cool','heat_cool','auto','dry','fan_only']}}}];return e;}
 async setConfig(c){if(!c.entity?.startsWith('climate.'))throw Error('Eine climate-Entity wird benötigt.');if(JSON.stringify(this._config)===JSON.stringify(c))return;this._config=c;const helpers=await window.loadCardHelpers();const native=await helpers.createCardElement({type:'thermostat',entity:c.entity,name:'',features:[]});const create=native.createRenderRoot?.bind(native);const sheet=new CSSStyleSheet();sheet.replaceSync(':host{height:205px!important;min-height:205px!important;max-height:205px!important}ha-card{border:0!important;border-radius:0!important;background:transparent!important;box-shadow:none!important;backdrop-filter:none!important;height:205px!important;min-height:205px!important;max-height:205px!important;padding:0!important;box-sizing:border-box}.title{display:none!important}.container{height:201px!important;display:flex;align-items:center;justify-content:center;padding:0!important}ha-state-control-climate-temperature{width:201px!important;max-width:201px!important;}');if(native.shadowRoot)native.shadowRoot.adoptedStyleSheets=[...native.shadowRoot.adoptedStyleSheets,sheet];else if(create)native.createRenderRoot=()=>{const r=create();r.adoptedStyleSheets=[...r.adoptedStyleSheets,sheet];return r;};native.hass=this.hass;this._native=native;await helpers.importMoreInfoControl('climate');}
 updated(){
 if(this._native)this._native.hass=this.hass;
 const s=this.hass?.states[this._config?.entity],bar=this.shadowRoot.querySelector('dash6-glass-segments');if(!s||!bar)return;
 if(this._selectedMode&&(s.state===this._selectedMode||s.state!==this._previousMode)){this._selectedMode=null;clearTimeout(this._modeTimer);}
 const icons={off:'mdi:power',heat:'mdi:fire',cool:'mdi:snowflake',heat_cool:'mdi:sun-snowflake',auto:'mdi:autorenew',dry:'mdi:water-percent',fan_only:'mdi:fan'};
 const modes=(this._config.modes||['off','heat','cool','heat_cool']).filter(mode=>(s.attributes.hvac_modes||[]).includes(mode));
 bar.configure({options:modes.map(mode=>({value:mode,label:this.hass.localize?.('component.climate.entity_component._.state.'+mode)||mode,icon:icons[mode]||'mdi:thermostat'})),value:this._selectedMode||s.state,label:'Modus',iconsOnly:true,disabled:this._modePending||['unknown','unavailable'].includes(s.state)});
 }
 connectedCallback(){super.connectedCallback();bindThemePreferences(this);this._positionPresets=()=>this.positionPresets();window.addEventListener('resize',this._positionPresets);window.addEventListener('scroll',this._positionPresets,true);window.visualViewport?.addEventListener('resize',this._positionPresets);}
 disconnectedCallback(){window.removeEventListener('resize',this._positionPresets);window.removeEventListener('scroll',this._positionPresets,true);window.visualViewport?.removeEventListener('resize',this._positionPresets);unbindThemePreferences(this);super.disconnectedCallback();clearTimeout(this._modeTimer);this._selectedMode=null;this.shadowRoot?.querySelector('dialog')?.close();}
 async selectMode(e){const value=e.detail.value;this._previousMode=this.hass.states[this._config.entity].state;this._selectedMode=value;this._modePending=true;try{await this.hass.callService('climate','set_hvac_mode',{entity_id:this._config.entity,hvac_mode:value});this._error='';}catch(error){this._selectedMode=null;reportError(this,error);}finally{this._modePending=false;clearTimeout(this._modeTimer);this._modeTimer=setTimeout(()=>{this._selectedMode=null;this.requestUpdate();},5000);}}

 async call(service,payload){try{await this.hass.callService('climate',service,{entity_id:this._config.entity,...payload});this._error='';}catch(e){reportError(this,e);}}
 openPresets(){
  const d=this.shadowRoot.querySelector('dialog'),b=this.shadowRoot.querySelector('.preset-button');if(d.open){d.close();return;}
  d.showModal();this.positionPresets();d.querySelector('[aria-checked=true]')?.focus({preventScroll:true});
 }
 positionPresets(){const d=this.shadowRoot.querySelector('dialog');if(!d?.open)return;const b=this.shadowRoot.querySelector('.preset-button').getBoundingClientRect(),v=window.visualViewport,left=v?.offsetLeft||0,top=v?.offsetTop||0,w=v?.width||innerWidth,h=v?.height||innerHeight;
  d.style.maxHeight=Math.max(44,h-24)+'px';d.style.overflowY='auto';const r=d.getBoundingClientRect(),x=Math.max(left+12,Math.min(b.right-r.width,left+w-r.width-12)),y=b.bottom+6+r.height<=top+h-12?b.bottom+6:Math.max(top+12,b.top-r.height-6);d.style.left=x+'px';d.style.top=Math.min(top+h-r.height-12,y)+'px';
 }

 async choosePreset(value){this.shadowRoot.querySelector('dialog').close();this._presetBusy=true;try{await this.call('set_preset_mode',{preset_mode:value})}finally{this._presetBusy=false;}}
 getCardSize(){return 6;}
 render(){const s=this.hass?.states[this._config?.entity];if(!s)return html``;const icons={off:'mdi:power',heat:'mdi:fire',cool:'mdi:snowflake',heat_cool:'mdi:sun-snowflake',auto:'mdi:autorenew',dry:'mdi:water-percent',fan_only:'mdi:fan'};const modes=(this._config.modes||['off','heat','cool','heat_cool']).filter(mode=>(s.attributes.hvac_modes||[]).includes(mode)),presets=s.attributes.preset_modes||[];return html`<style>${surface}</style><ha-card>${this._native}<div class="features">${errorIndicator(this)}<dash6-glass-segments class="climate-modes" style=${"width:"+(modes.length*44+8)+"px"} @selection-changed=${this.selectMode}></dash6-glass-segments>${presets.length?html`<button class="preset-button" aria-label="Preset auswählen" aria-haspopup="menu" ?disabled=${this._presetBusy||['unknown','unavailable'].includes(s.state)} @click=${this.openPresets}><ha-attribute-icon .stateObj=${s} .attribute=${'preset_mode'} .attributeValue=${s.attributes.preset_mode}></ha-attribute-icon></button>`:''}</div></ha-card><dialog @click=${e=>{if(e.target===e.currentTarget)e.currentTarget.close()}}><div role="menu" aria-label="Thermostat-Preset">${presets.map(value=>html`<button role="menuitemradio" aria-checked=${String(value===s.attributes.preset_mode)} @click=${()=>this.choosePreset(value)}><span class="check">${value===s.attributes.preset_mode?'✓':''}</span>${this.hass.localize?.('component.climate.entity_component._.state_attributes.preset_mode.state.'+value)||value}</button>`)}</div></dialog>`;}
}
customElements.define('dash6-thermostat-card',ThermostatCard);
window.customCards??=[];window.customCards.push({type:'dash6-thermostat-card',name:'DASH6 Dual-Thermostat',description:'Native Dual-Temperaturbedienung mit Modus und Preset ohne Card-Mod.',preview:true});
