import {SWITCH_SCHEMA} from './glass-switch.js';
import './config-editor.js';
import {LitElement,html,css} from 'lit';
import DEFAULT from './vacuum-default.json';
class VacuumEditor extends LitElement {
 static properties={hass:{attribute:false},_config:{state:true}};
 static styles=css`:host{display:block}.grid{display:grid;gap:12px}.row{display:grid;grid-template-columns:1fr 1fr;gap:8px}button{min-height:44px;margin:4px}h3{margin:16px 0 8px}`;
 setConfig(config){this._config={...DEFAULT,...structuredClone(config),entities:{...DEFAULT.entities,...config.entities}};}
 change(patch){this._config={...this._config,...patch};this.dispatchEvent(new CustomEvent('config-changed',{detail:{config:this._config},bubbles:true,composed:true}));}
 form(data,schema,update){return html`<ha-form .hass=${this.hass} .data=${data} .schema=${schema} .computeLabel=${x=>x.label||x.name} @value-changed=${e=>{e.stopPropagation();update(e.detail.value)}}></ha-form>`;}
 render(){if(!this._config)return html``;const c=this._config;
 const labels={battery:'Batterie',progress:'Fortschritt',mode:'Reinigungsmodus',intensity:'Wischintensität',route:'Wischmodus',emptyMode:'Entleerungsmodus',drying:'Mopp-Trocknung',washing:'Moppwäsche',emptying:'Staubentleerung',dryTime:'Trocknungsrestzeit',cleanWater:'Frischwassertank',dirtyWater:'Schmutzwassertank'};
 return html`<div class="grid">${this.form(c,[{name:'entity',label:'Staubsauger',required:true,selector:{entity:{domain:'vacuum'}}},...SWITCH_SCHEMA],v=>this.change(v))}
 <h3>Standard-Reinigung</h3>${this.form(c.defaults||{mode:'vac_and_mop',intensity:'moderate',route:'standard',fan:'balanced',repeat:1},[{name:'mode',label:'Modus',selector:{select:{options:['vac_and_mop','vacuum','mop']}}},{name:'intensity',label:'Wischintensität',selector:{select:{options:['off','slight','low','moderate','high','extreme']}}},{name:'route',label:'Wischmodus',selector:{select:{options:['standard','deep','deep_plus','fast']}}},{name:'fan',label:'Saugstufe',selector:{select:{options:['quiet','balanced','turbo','max','max_plus']}}},{name:'repeat',label:'Durchgänge',selector:{number:{min:1,max:3,mode:'box'}}}],v=>this.change({defaults:v}))}<h3>Dock und Zustände</h3>${this.form(c.entities,Object.entries(labels).map(([name,label])=>({name,label,selector:{entity:{domain:DEFAULT.entities[name]?.split('.')[0]}}})),v=>this.change({entities:v}))}
 ${['default','cleaning'].map(group=>html`<h3>${group==='default'?'Wartungswerte':'Werte während der Reinigung'}</h3>${c.stats[group].map((stat,i)=>html`<div>${this.form(stat,[{name:'entity',label:'Messwert',selector:{entity:{domain:'sensor'}}},{name:'title',label:'Beschriftung',selector:{text:{}}},{name:'unit',label:'Einheit (Sensorwert wird nicht umgerechnet)',selector:{text:{}}},{name:'scale',label:'Nachkommastellen',selector:{number:{min:0,max:5,mode:'box'}}}],v=>{const stats=structuredClone(c.stats);stats[group][i]=v;this.change({stats})})}${group==='default'?this.form({reset:c.reset_buttons?.[stat.title]},[{name:'reset',label:'Reset-Button (zweite Bestätigung bleibt erforderlich)',selector:{entity:{domain:'button'}}}],v=>this.change({reset_buttons:{...c.reset_buttons,[stat.title]:v.reset}})):''}<button @click=${()=>{const stats=structuredClone(c.stats);stats[group].splice(i,1);this.change({stats})}}>Entfernen</button></div>`)}<button @click=${()=>{const stats=structuredClone(c.stats);stats[group].push({entity:'',title:'',unit:'',scale:0});this.change({stats})}}>Messwert hinzufügen</button>`)}
 <h3>Räume und bestätigte Roborock-Segmente</h3>${c.areas.map((area,i)=>html`<div>${this.form(area,[{name:'area_id',label:'HA-Bereich',selector:{area:{}}},{name:'roborock_area_id',label:'Roborock-Segment-ID',selector:{number:{min:1,max:255,mode:'box'}}}],v=>{const areas=structuredClone(c.areas);areas[i]=v;this.change({areas})})}<button @click=${()=>this.change({areas:c.areas.filter((_,n)=>n!==i)})}>Raum entfernen</button></div>`)}<button @click=${()=>this.change({areas:[...c.areas,{area_id:'',roborock_area_id:1}]})}>Raum hinzufügen</button>
 <details><summary>Alle Einstellungen einschließlich Darstellung und Aktionen</summary><dash6-config-editor .hass=${this.hass} ._config=${c} @config-changed=${e=>{e.stopPropagation();this._config=structuredClone(e.detail.config);this.dispatchEvent(new CustomEvent('config-changed',{detail:{config:this._config},bubbles:true,composed:true}));}}></dash6-config-editor></details></div>`;
 }
}
customElements.define('dash6-vacuum-editor',VacuumEditor);
